### PR TITLE
Bump to Kogito 0.13.1

### PR DESCRIPTION
**Pull request by evacchi**
:crossed_fingers:

### CODE REVIEW

**Comment by evacchi** [comment]
@gsmet @geoand is it ok or should we restart this? can we promote to central?

**Comment by gsmet** [comment]
Let me run the build locally.

**Comment by gsmet** [comment]
@evacchi works locally, I think you can proceed.

**Comment by evacchi** [comment]
thanks @gsmet /cc @radtriste fasten your seatbelts

**Comment by evacchi** [comment]
@gsmet artifacts deployed to central!

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
