### PR TITLE
Unlist quarkus-resteasy-qute and quarkus-resteasy-reactive-qute

### PR DESCRIPTION
**Pull request by ia3andy**
part of #37000

### CODE REVIEW

**Comment by ia3andy** [comment]
cc @mkouba @gsmet

**Review by mkouba — APPROVED** [review]
Looks good.

**Comment by aloubyansky** [comment]
Was there a PR unlisting these in core?

**Comment by ia3andy** [comment]
@aloubyansky should we unlist them in core? if that's the case we don't need to do it here...

**Comment by aloubyansky** [comment]
Yes, they should be unlisted in core unless there is a reason not to.

**Comment by ia3andy** [comment]
@aloubyansky ah but they should be also unlisted here (just for this next platform release as it's not yet in core)

**Comment by aloubyansky** [comment]
Sure, no problem.

**Review by gsmet — APPROVED** [review]
OK, let's merge it for now and, ideally, let's drop it when fixed in core.

**Pull request merged**
