### PR TITLE
Temporarily disable camel-jta tests

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Hm... The PR seems to have failed in CI

**Comment by jamesnetherton** [comment]
Probably due to this https://github.com/apache/camel-quarkus/issues/1370.

Can you rerun the workflow?

**Comment by geoand** [comment]
Jobs restarted

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
