### PR TITLE
adding metadata for extensions

### PR DESCRIPTION
**Pull request by vardhmanJain**
adding extensions metadata for 2.7 Quarkus

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by vardhmanJain** [comment]
@aloubyansky I had one question.
on upstream quarkus there's this commit - https://github.com/quarkusio/quarkus/pull/24522/files, that sets the status of stork to "preview"(this commit will be later cherry-picked in our internal mirror)
also in this pr i have updated the status of stork to "tech preview"
will this cause any issues?

**Comment by aloubyansky** [comment]
No, it's a different metadata element.  So it will eventually have status 'preview' and redhat-support 'tech-preview'.

**Comment by vardhmanJain** [comment]
> No, it's a different metadata element. So it will eventually have status 'preview' and redhat-support 'tech-preview'.

Okay...Thanks!

**Comment by aloubyansky** [comment]
@vardhmanJain could you please squash the commits?

**Comment by vardhmanJain** [comment]
> @vardhmanJain could you please squash the commits?

yes..on it.

**Pull request merged**
