### PR TITLE
PLANNER-2439 Use optaplanner-build-parent as in input BOM

### PR DESCRIPTION
**Pull request by rsynek**
This PR has to be merged after merging https://github.com/kiegroup/optaplanner/pull/1473 and releasing the OptaPlanner 8.10.0.Final.

### CODE REVIEW

**Comment by rsynek** [comment]
FYI: @aloubyansky

**Comment by aloubyansky** [comment]
These tests don't seem to exist
````
Warning:  The POM for org.optaplanner:optaplanner-quarkus-devui-integration-test:jar:8.8.0.Final is missing, no dependency information available
Warning:  The POM for org.optaplanner:optaplanner-quarkus-devui-integration-test:jar:tests:8.8.0.Final is missing, no dependency information available
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/optaplanner/optaplanner-quarkus-devui-integration-test/8.8.0.Final/optaplanner-quarkus-devui-integration-test-8.8.0.Final.jar
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/optaplanner/optaplanner-quarkus-devui-integration-test/8.8.0.Final/optaplanner-quarkus-devui-integration-test-8.8.0.Final-tests.jar
````

**Comment by aloubyansky** [comment]
I guess they are included in the upcoming release?

**Comment by rsynek** [comment]
Exactly. I added new modules that are already available on the main branch as this PR has to wait for 8.10.0.Final release anyway (cut-off is this Friday).

**Comment by rsynek** [comment]
@aloubyansky could we please retrigger the build? OptaPlanner 8.10.0.Final is already out:
https://repo.maven.apache.org/maven2/org/optaplanner/optaplanner-core/8.10.0.Final/

**Comment by aloubyansky** [comment]
@rsynek sure, just did, thanks for the update. Could you please include the changes to the `generated-platform-project` as well in the PR?

**Comment by aloubyansky** [comment]
````
 Failed to execute goal on project optaplanner-quarkus-devui-integration-test: Could not resolve dependencies for project io.quarkus.platform:optaplanner-quarkus-devui-integration-test:jar:999-SNAPSHOT: The following artifacts could not be resolved: org.optaplanner:optaplanner-quarkus-devui-integration-test:jar:8.8.0.Final, org.optaplanner:optaplanner-quarkus-devui-integration-test:jar:tests:8.8.0.Final: Could not find artifact org.optaplanner:optaplanner-quarkus-devui-integration-test:jar:8.8.0.Final in central (https://repo.maven.apache.org/maven2)
````

**Comment by aloubyansky** [comment]
It's looking for 8.8.0, while the test exists only in 8.10.0

**Comment by aloubyansky** [comment]
You should probably rebase your branch @rsynek and upgrade the version to 8.10.0.Final.

**Comment by rsynek** [comment]
I thought the version upgrade was part of the PR from start, sorry for that.

**Comment by aloubyansky** [comment]
@rsynek have you included all the changes to the `generated-platform-project`? It doesn't look like it. There must be some BOM updates. Also, please, squash the commits once you are done. Thanks!

**Comment by gsmet** [comment]
To clarify, please run `mvn process-sources` and commit what you get.

**Comment by rsynek** [comment]
@aloubyansky @gsmet I committed 3 additional pom.xml files that have been generated under `generated-platform-project/quarkus-optaplanner/integration-tests` (the 3 new test modules). Running `mvn process-sources` does not introduce any additional changes in my local git repository.

**Comment by aloubyansky** [comment]
I'll try your branch locally a bit later today to check.

**Comment by aloubyansky** [comment]
@rsynek just checking out your branch and running `mvn clean process-resources` I get
````
[aloubyansky@localhost quarkus-platform]$ git status
On branch PLANNER-2439
Your branch is up to date with 'rsynek/PLANNER-2439'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   generated-platform-project/quarkus-optaplanner/bom/pom.xml
	modified:   generated-platform-project/quarkus-optaplanner/integration-tests/pom.xml
	modified:   generated-platform-project/quarkus-universe/bom/pom.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	generated-platform-project/quarkus-optaplanner/integration-tests/optaplanner-quarkus-devui-integration-test/src/
	generated-platform-project/quarkus-optaplanner/integration-tests/optaplanner-quarkus-drl-integration-test/src/
	generated-platform-project/quarkus-optaplanner/integration-tests/optaplanner-quarkus-integration-test/src/

no changes added to commit (use "git add" and/or "git commit -a")
````

**Comment by rsynek** [comment]
Ah, it's `process-resources`, not `process-sources`. Should be OK now. Thanks @aloubyansky!

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
Now we can see your thirdparty dependencies, great! Thanks @rsynek

**Pull request merged**
