### PR TITLE
Upgrade to quarkus 1.1.0.Final and camel-quarkus 1.0.0-M2

### PR DESCRIPTION
**Pull request by ppalaga**
This is waiting for the public availability of Camel Quarkus 1.0.0-M2. 
All tests (incl. native) are passing.

### CODE REVIEW

**Comment by ppalaga** [comment]
cc @lburgazzoli

**Comment by ppalaga** [comment]
Camel Quarkus 1.0.0-M2 is available now http://central.maven.org/maven2/org/apache/camel/quarkus/camel-quarkus-bom/1.0.0-M2/

**Comment by gsmet** [comment]
@ppalaga Thanks.

I'm merging this one but there is a small issue: some generated files were committed to the repository and are updated for each build (at least they got updated when I built them locally):
```
	modified:   integration-tests/camel-sjms/data/bindings/activemq-bindings-1.bindings
	modified:   integration-tests/camel-sjms/data/bindings/activemq-bindings-2.bindings
	modified:   integration-tests/camel-sjms/data/journal/activemq-data-1.amq
	modified:   integration-tests/camel-sjms/data/journal/activemq-data-2.amq
```

Any chance you could have a look when you're back next year? Thanks!

**Comment by gsmet** [comment]
@ppalaga I fixed it here.

**Pull request merged**
