### PR TITLE
Kogito 1.17.0.Final + OptaPlanner 8.17.0.Final

### PR DESCRIPTION
**Pull request by mbiarnes**
Contains staging repos that should be removed once the Kogito and OptaPlanner artifacts are in Maven Central

### CODE REVIEW

**Comment by radtriste** [comment]
@aloubyansky @gsmet we are all good on that one :)

**Comment by radtriste** [comment]
@mbiarnes can you squash ? :)

**Comment by mbiarnes** [comment]
squashed

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
@radtriste @mbiarnes is this targeting 2.7 or 2.8?

**Comment by radtriste** [comment]
@aloubyansky This is 2.7

**Pull request merged**
