### PR TITLE
Bump to Kogito 0.11.1

### PR DESCRIPTION
**Pull request by evacchi**
We are pushing to Central on Mon/Tue.
  In the meantime, we give it a try using this staging repo

### CODE REVIEW

**Comment by gsmet** [comment]
Looks good, please ping me when you removed the staging repo from the PR.

**Comment by evacchi** [comment]
should be done tomorrow morning, thanks @gsmet

**Comment by evacchi** [comment]
@gsmet just bumped, let's wait for CI /cc @mariofusco

**Comment by evacchi** [comment]
all green @gsmet !

**Pull request merged**
