### PR TITLE
Upgrade to Camel Quarkus 1.3.0

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by gsmet** [comment]
@ppalaga CI is OK with your changes. I'll let you update the PR to remove the staging repo commit when you have them released?

Please be careful: keep my additional commit :).

**Comment by ppalaga** [comment]
Thanks, I will

**Comment by ppalaga** [comment]
Staging repos removed

**Comment by gsmet** [comment]
Had to force-push something to trigger CI.

**Comment by gsmet** [comment]
The build failed with:
```
[FATAL] Non-resolvable parent POM for org.apache.camel.quarkus:camel-quarkus-bom:1.3.0: Could not find artifact org.apache.camel.quarkus:camel-quarkus-poms:pom:1.3.0 in central (https://repo.maven.apache.org/maven2) @ org.apache.camel.quarkus:camel-quarkus-bom:1.3.0, /home/vsts/.m2/repository/org/apache/camel/quarkus/camel-quarkus-bom/1.3.0/camel-quarkus-bom-1.3.0.pom, line 23, column 13
[FATAL] Non-resolvable parent POM for org.apache.camel.quarkus:camel-quarkus-bom:1.3.0: Failure to find org.apache.camel.quarkus:camel-quarkus-poms:pom:1.3.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ org.apache.camel.quarkus:camel-quarkus-bom:1.3.0, /home/vsts/.m2/repository/org/apache/camel/quarkus/camel-quarkus-bom/1.3.0/camel-quarkus-bom-1.3.0.pom, line 23, column 13
 @ 
```
I will retry later.

**Comment by ppalaga** [comment]
Yeah, looks like the sync to Central has not fully finished yet.

**Comment by gsmet** [comment]
I restarted the run.

**Review by oscerd — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
