### PR TITLE
Upgrade Quarkus to 3.0.1

### PR DESCRIPTION
**Pull request by aloubyansky**
Also upgrade the platform generator to 0.0.88 that filters out test scoped dependencies.

Supersedes https://github.com/quarkusio/quarkus-platform/pull/822

### CODE REVIEW

**Comment by aloubyansky** [comment]
Ha, here you go @metacosm
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor#createConfigurationServiceAndOperator threw an exception: java.lang.RuntimeException: Incompatible Quarkus version found: "3.0.1.Final", expected: "3.0.0.Final"
```
So, we disable JOSDK after all?

**Comment by maxandersen** [comment]
that version check cannot be right. yeah; operator SDK will have to be removed from platform until it does not hard fail on even the slightest dependency update.

**Comment by aloubyansky** [comment]
To potentially save @gsmet's time, here is a PR upgrading to 3.0.1 and disabling JOSDK https://github.com/quarkusio/quarkus-platform/pull/825

**Comment by gsmet** [comment]
Yes, I won't have the time to wait for another release of the JOSDK so let's drop it...

@metacosm we release Quarkus every week, I don't see how adding this check could be a good idea, we need to drop it.

**Pull request merged**
