### PR TITLE
[RHPAM-4034] Exclude more Kogito Spring related dependencies

### PR DESCRIPTION
**Pull request by AntStephenson**
Exclude more Kogito Spring related dependencies from bomGenerator. 

Related JIRA: https://issues.redhat.com/browse/RHPAM-4034

### CODE REVIEW

**Comment by AntStephenson** [comment]
@aloubyansky Hi, here is the PR - I could not assign a `backport-2.2` label (probably a permission issue, maybe you need to be a contributor?)

**Comment by aloubyansky** [comment]
@AntStephenson thanks, have you run `./mvnw -Dsync` before opening the PR?

**Comment by AntStephenson** [comment]
No I didn't, will do that now, thanks!

**Comment by AntStephenson** [comment]
Should be fixed now

**Pull request merged**
