### PR TITLE
Upgrade Amazon Services to 1.4.0

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@aloubyansky I'm not sure what's going on but since the integration of Drools, the project generation seems to be unstable. I'm positive I ran the sync locally (checked twice with both JDK 11 and JDK 17) and I get a diff in CI:

```
diff --git a/generated-platform-project/quarkus-drools/bom/pom.xml b/generated-platform-project/quarkus-drools/bom/pom.xml
index 9876a49..ba38fe9 100644
--- a/generated-platform-project/quarkus-drools/bom/pom.xml
+++ b/generated-platform-project/quarkus-drools/bom/pom.xml
@@ -435,17 +435,6 @@
         <artifactId>glazedlists_java15</artifactId>
         <version>1.8.0</version>
       </dependency>
-      <dependency>
-        <groupId>org.antlr4gwt</groupId>
-        <artifactId>antlr4gwt-runtime</artifactId>
-        <version>4.10.0</version>
-      </dependency>
-      <dependency>
-        <groupId>org.antlr4gwt</groupId>
-        <artifactId>antlr4gwt-runtime</artifactId>
-        <version>4.10.0</version>
-        <classifier>sources</classifier>
-      </dependency>
       <dependency>
         <groupId>org.antlr</groupId>
         <artifactId>ST4</artifactId>
@@ -[23](https://github.com/quarkusio/quarkus-platform/actions/runs/3731767475/jobs/6330367303#step:8:24)91,29 +2380,6 @@
         <artifactId>powermock-module-junit4</artifactId>
         <version>2.0.7</version>
       </dependency>
-      <dependency>
-        <groupId>org.rikkola.gwt</groupId>
-        <artifactId>antlr4-c3-gwt</artifactId>
-        <version>1.1.12</version>
-        <exclusions>
-          <exclusion>
-            <groupId>org.glassfish</groupId>
-            <artifactId>javax.json</artifactId>
-          </exclusion>
-        </exclusions>
-      </dependency>
-      <dependency>
-        <groupId>org.rikkola.gwt</groupId>
-        <artifactId>antlr4-c3-gwt</artifactId>
-        <version>1.1.12</version>
-        <classifier>sources</classifier>
-        <exclusions>
-          <exclusion>
-            <groupId>org.glassfish</groupId>
-            <artifactId>javax.json</artifactId>
-          </exclusion>
-        </exclusions>
-      </dependency>
       <dependency>
         <groupId>org.slf4j</groupId>
         <artifactId>jcl-over-slf4j</artifactId>
@@ -[24](https://github.com/quarkusio/quarkus-platform/actions/runs/3731767475/jobs/6330367303#step:8:25)83,11 +2449,6 @@
         <version>2.8.2</version>
         <scope>test</scope>
       </dependency>
-      <dependency>
-        <groupId>xerces</groupId>
-        <artifactId>xercesImpl</artifactId>
-        <version>2.12.0.SP04</version>
-      </dependency>
       <dependency>
         <groupId>xmlunit</groupId>
         <artifactId>xmlunit</artifactId>
```

FWIW, the other day, two subsequent runs gave me two different results. I'm unsure of what's going on.

**Comment by gsmet** [comment]
Running with `./mvnw -Dsync -s .github/mvn-settings.xml` get me the same result as in CI.

When doing a normal build, I see a few things coming from JBoss Nexus. I wonder if there are different versions of the artifacts in some repositories.

**Comment by aloubyansky** [comment]
Most probably you have some Maven repositories enabled locally that aren't enabled in the platform project. For example xercesImpl 2.12.0.SP04 is available in the JBoss repo but not Central.

**Comment by gsmet** [comment]
Hmmm, actually, you're right. I thought I got rid of this configuration a long time ago but it was still there.

**Pull request merged**
