### PR TITLE
Upgrade to Camel Quarkus 2.5.0

### PR DESCRIPTION
**Pull request by zbendhiba**
**Camel 3.13.0**

Camel Quarkus extensions have been upgraded to Camel 3.13.0 version, that brings a list of improvements and fixes. Check the [Camel 3.13.0 release notes](https://camel.apache.org/releases/release-3.13.0/).

### CODE REVIEW

**Comment by zbendhiba** [comment]
Can someone tag this release with  _release/noteworthy-feature_ ?

**Comment by aloubyansky** [comment]
@zbendhiba could you please prepare the text for the noteworthy features which we could copy the announcement? Here is how we usually do it https://quarkus.io/blog/quarkus-2-4-0-final-released/#whats-new. Thanks.

**Comment by zbendhiba** [comment]
> @zbendhiba could you please prepare the text for the noteworthy features which we could copy the announcement? Here is how we usually do it https://quarkus.io/blog/quarkus-2-4-0-final-released/#whats-new. Thanks.

Is the description of the PR not okay ?

**Comment by aloubyansky** [comment]
Have a look at the announcement I referenced as an example. We do link the changelog. But if there is something we want to highlight/promote, we add a few sentences sentences.

So, I think we could simply reference your changelog too, right @gsmet? If there is some text you want to appear in the announcement, please, let us know.

**Comment by zbendhiba** [comment]
> Have a look at the announcement I referenced as an example. We do link the changelog. But if there is something we want to highlight/promote, we add a few sentences in the announcement.
> 
> So, I think we could simply reference your changelog too, right @gsmet? If there is some text you want to appear in the announcement, please, let us know.

This is all what we have for this release. No new feature to highlight. Thanks

**Review by gsmet — CHANGES_REQUESTED** [review]
@zbendhiba could you squash the 2 commits?

**Comment by zbendhiba** [comment]
> @zbendhiba could you squash the 2 commits?

yes

**Comment by zbendhiba** [comment]
@gsmet It should be fine now

**Review by aloubyansky — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Pull request merged**
