### PR TITLE
Update Camel Quarkus to 1.0.0-M5

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@lburgazzoli @ppalaga got this from CI:
```
[ERROR] Failed to execute goal org.l2x6.rpkgtests:rpkgtests-maven-plugin:0.7.0:rpkgtests (rpkgtests) on project quarkus-universe-integration-tests-rpkgtests: Could not download org.apache.camel.quarkus:camel-quarkus-integration-test-core-main-xml:1.0.0-M5: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.apache.camel.quarkus:camel-quarkus-integration-test-core-main-xml:jar:tests:1.0.0-M5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
```
I suspect there were some changes on your side?

**Comment by ppalaga** [comment]
Let me have a look.

**Comment by gsmet** [comment]
Feel free to push to this PR.

**Comment by ppalaga** [comment]
Superceded by https://github.com/quarkusio/quarkus-platform/pull/33

**Pull request closed without merging**
