### PR TITLE
Kogito 1.16.1.Final + OptaPlanner 8.16.1.Final

### PR DESCRIPTION
**Pull request by radtriste**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by aloubyansky** [comment]
````
2022-01-31T22:26:34.8543780Z [ERROR] Errors: 
2022-01-31T22:26:34.8545244Z [ERROR]   CustomEndpointIT » IllegalState Unable to locate the artifact metadata file cr...
2022-01-31T22:26:34.8545906Z [ERROR]   DMNIT » IllegalState Unable to locate the artifact metadata file created that ...
2022-01-31T22:26:34.8547202Z [ERROR]   KogitoDMNCodeCodestartIT.testContent:53 » NullPointer
2022-01-31T22:26:34.8547529Z [INFO] 
2022-01-31T22:26:34.8548517Z [ERROR] Tests run: 4, Failures: 0, Errors: 3, Skipped: 0
2022-01-31T22:26:34.8548792Z [INFO] 
2022-01-31T22:26:34.8563379Z [INFO] 
2022-01-31T22:26:34.8565257Z [INFO] --- maven-failsafe-plugin:2.22.0:verify (default) @ kogito-quarkus-decisions-integration-test ---
````
The first two tests are `QuarkusIntegrationTest`s, which means they expect a packaged app, so `<packageApplication>true</packageApplication>`. I am not yet sure what causes the NPE.

**Comment by radtriste** [comment]
```
2022-02-01T08:40:28.8373227Z [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 42.662 s <<< FAILURE! - in org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT
2022-02-01T08:40:28.8375962Z [ERROR] testContent  Time elapsed: 0.119 s  <<< ERROR!
2022-02-01T08:40:28.8376487Z java.lang.NullPointerException
2022-02-01T08:40:28.8377387Z 	at org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT.testContent(KogitoDMNCodeCodestartIT.java:53)
```

looks like https://github.com/kiegroup/kogito-runtimes/blob/173b53ac4634dfe2c4c31e6db25c4d52a15f6195/quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/KogitoDMNCodeCodestartIT.java#L43 is null ?

anyway will (re)disable this test for now

**Comment by radtriste** [comment]
Kogito on Central ... https://search.maven.org/artifact/org.kie.kogito/kogito-build-parent/1.16.1.Final/pom

**Comment by gsmet** [comment]
I rebased, squashed, reenabled Kogito and reenabled an OptaPlanner test that should have been reenabled long ago.

Let's see what CI says!

**Comment by gsmet** [comment]
All green, thanks!

**Pull request merged**
