### PR TITLE
Upgrade to Quarkus core 2.7.0.Final and platform generator 0.0.46

### PR DESCRIPTION
**Pull request by aloubyansky**
The platform generator adds a new option for tests that looks like
````
<test>
    <artifact>org.kie.kogito:kogito-quarkus-serverless-workflow-integration-test:${kogito-quarkus.version}</artifact>
    <packageApplication>true</packageApplication>
</test>
````
enabling packaging the test application, which is required to support `QuarkusIntegrationTest`s.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Cool, thanks!

**Comment by aloubyansky** [comment]
@gsmet I added a commit to skip the Blaze Persistence test.

**Comment by beikov** [comment]
There it is @gsmet https://github.com/quarkusio/quarkus-platform/pull/458

**Pull request merged**
