### PR TITLE
Upgrade to Camel Quarkus 3.15.0, Quarkus CXF 3.15.1 and Amazon Services 2.18.1

### PR DESCRIPTION
**Pull request by ppalaga**
cc @jamesnetherton

### CODE REVIEW

**Comment by ppalaga** [comment]
I am also upgrading Amazon Services to 2.18.1, because 2.18.0 does not provide test jars

**Comment by aloubyansky** [comment]
@ppalaga I just merged the Amazon Services 2.18.1 upgrade, could you please rebase? The CI was running when you opened this one. Thanks.

**Comment by jamesnetherton** [comment]
Need a PR for the 3.15 branch also.

**Comment by jamesnetherton** [comment]
I took the liberty of creating another PR to fix the conflicts and work around the test failures.

https://github.com/quarkusio/quarkus-platform/pull/1297

**Pull request closed without merging**
