### PR TITLE
Upgrade Camel Quarkus to 3.0.0-RC2  and Google Cloud Services to 2.2.0

### PR DESCRIPTION
**Pull request by loicmathieu**
@jamesnetherton this should fix the issue with Google Cloud services in Camel.

@gsmet please also backport it to 3.2.

### CODE REVIEW

**Comment by loicmathieu** [comment]
Sorry @aloubyansky, I added it to the commit.

**Comment by aloubyansky** [comment]
@loicmathieu how do these failures look to you?

**Comment by jamesnetherton** [comment]
I don't get why `com.google.api:gax-*` is being resolved as `2.19.1`. We'd expect `2.31.1`.

**Comment by aloubyansky** [comment]
@jamesnetherton what would introduce `2.31.1`?

**Comment by jamesnetherton** [comment]
> @jamesnetherton what would introduce `2.31.1`?

This PR and the upgrade to the latest Google Cloud libs.

If you browse the dependency tree from `quarkiverse/quarkus-google-cloud-services` you see:

```
$ mvn dependency:tree -Dincludes="com.google.api:gax-*"

[INFO] io.quarkiverse.googlecloudservices:quarkus-google-cloud-services-main-it:jar:1.3.0-SNAPSHOT
[INFO] \- io.quarkiverse.googlecloudservices:quarkus-google-cloud-storage:jar:1.3.0-SNAPSHOT:compile
[INFO]    \- com.google.cloud:google-cloud-storage:jar:2.25.0:compile
[INFO]       +- com.google.api:gax-httpjson:jar:2.31.1:compile
[INFO]       +- com.google.api:gax:jar:2.31.1:compile
[INFO]       \- com.google.api:gax-grpc:jar:2.31.1:compile
```

But in the platform we see:

```
$ mvn dependency:tree -Dincludes="com.google.api:gax-*"

[INFO] io.quarkus.platform:quarkus-google-cloud-services-main-it:jar:999-SNAPSHOT
[INFO] \- io.quarkiverse.googlecloudservices:quarkus-google-cloud-services-main-it:jar:2.2.0:compile
[INFO]    \- io.quarkiverse.googlecloudservices:quarkus-google-cloud-storage:jar:2.2.0:compile
[INFO]       \- com.google.cloud:google-cloud-storage:jar:2.25.0:compile
[INFO]          +- com.google.api:gax-httpjson:jar:2.31.1:compile
[INFO]          +- com.google.api:gax:jar:2.19.1:compile
[INFO]          \- com.google.api:gax-grpc:jar:2.19.1:compile
```

**Comment by aloubyansky** [comment]
It's due to the `quarkus-bom` including
```
<dependency>
    <groupId>com.google.api.grpc</groupId>
    <artifactId>proto-google-common-protos</artifactId>
    <version>2.19.1</version>
</dependency>
```
from https://github.com/googleapis/sdk-platform-java resulting in
Screenshot from 2023-08-07 14-35-06

**Comment by loicmathieu** [comment]
@jamesnetherton it's not the first time we have an issue due to this library that is not updated at Quarkus side. I have no idea how we can work around that.

**Comment by aloubyansky** [comment]
I opened https://github.com/quarkusio/quarkus/pull/35239

**Comment by aloubyansky** [comment]
In the meantime, we could apply the following to the platform
```
diff --git a/pom.xml b/pom.xml
index 995d60b61..5f6f920ec 100644
--- a/pom.xml
+++ b/pom.xml
@@ -188,6 +188,8 @@
                                     <dependency>io.quarkiverse.vault:quarkus-vault:${quarkus-vault.version}</dependency>
                                     <dependency>io.quarkiverse.vault:quarkus-vault-deployment:${quarkus-vault.version}</dependency>
                                     <dependency>io.quarkiverse.vault:quarkus-vault-model:${quarkus-vault.version}</dependency>
+                                    <!-- temporary enforce 2.31.1 until https://github.com/quarkusio/quarkus/pull/35239 makes its way in -->
+                                    <dependency>com.google.api.grpc:proto-google-common-protos:2.31.1</dependency>
```

**Comment by aloubyansky** [comment]
Oh, it actually doesn't exist in that version

**Comment by aloubyansky** [comment]
So they use the same repo but release submodules under different versions. I'll have a look a bit later how to handle this better.

**Comment by loicmathieu** [comment]
I opened https://github.com/quarkusio/quarkus/pull/35283 to upgrade the lib at Quarkus side.

**Comment by gsmet** [comment]
I made some adjustments and also included the Camel Quarkus update here to check we can come up with something working with both updated.

**Comment by gsmet** [comment]
OK, it doesn't look worse. I will try to backport it to 3.2 where we have a cleaner status.

**Comment by loicmathieu** [comment]
@gsmet we really need to have https://github.com/quarkusio/quarkus/pull/35283 merged first, that would make this PR to be green I think.

**Comment by aloubyansky** [comment]
@loicmathieu AFAICS, it'd be equivalent to what @gsmet added to this PR.

**Comment by jamesnetherton** [comment]
Can we try adding overrides for the gax misalignment? E.g:

```
<dependency>com.google.api:gax:2.31.1</dependency>
<dependency>com.google.api:gax:2.31.1:testlib</dependency>
<dependency>com.google.api:gax-grpc:2.31.1</dependency>
<dependency>com.google.api:gax-grpc:2.31.1:testlib</dependency>
```

**Comment by loicmathieu** [comment]
This PR cannot work as it can only be merged on Quarkus 3.2 now that the removal of bootstrap config is merged.

**Pull request closed without merging**
