### PR TITLE
Upgrade to Google Cloud Services 2.4.0

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by loicmathieu** [comment]
Test failure seems unrelated:
```
Caused by: java.lang.IllegalStateException: Cannot set quarkus.http.redirect-insecure-requests without enabling SSL.
```

**Comment by aloubyansky** [comment]
@loicmathieu could you run `./mvnw -Dsync` and commit the changes though, please?

**Comment by loicmathieu** [comment]
I did it but not include all changes because, for an unknown reason, it changes unrelated version (version of Quarkus extensions!).
I double check if I miss something.

**Comment by loicmathieu** [comment]
@aloubyansky I added a commit to fix some issues with CXF dependency using a fixed version instead of a property.

Maven also updated the `quarkus-qpid-jms-integration-test` pom to use a fixed version instead of a property, I didn't commit it as it seems a bug to me.

**Comment by aloubyansky** [comment]
That's ok, please, always include all the changes, otherwise, it'll complain.

The generator prefers properties instead of specific values, it looks like both CXF and GCS extensions had the same versions but used different properties, now that you upgraded your extensions to 2.4.0 it became unambiguous and it replaced the CXF 2.3.0 with its property.

**Comment by loicmathieu** [comment]
OK, I'll added the Qpid changes then

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
I fixed the issue and force pushed.

**Pull request merged**
