### PR TITLE
Upgrade to Quarkus 2.14.0.CR1

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
The platform situation is pretty bad:
- Camel Quarkus tests are failing because of:
```
2022-10-26T13:59:18.9016369Z Caused by: java.lang.ClassCastException: class org.jboss.jandex.MethodParameterInfo cannot be cast to class org.jboss.jandex.Type (org.jboss.jandex.MethodParameterInfo and org.jboss.jandex.Type are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @68e5c7ae)
2022-10-26T13:59:18.9017743Z 	at org.apache.camel.quarkus.core.deployment.InjectionPointsProcessor.injectedComponents(InjectionPointsProcessor.java:130)
2022-10-26T13:59:18.9018549Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-26T13:59:18.9019213Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-10-26T13:59:18.9019954Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-10-26T13:59:18.9020558Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-10-26T13:59:18.9021050Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
2022-10-26T13:59:18.9021613Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
2022-10-26T13:59:18.9022093Z 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2022-10-26T13:59:18.9022635Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-10-26T13:59:18.9023235Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-10-26T13:59:18.9023720Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-26T13:59:18.9024136Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```
- Debezium tests are failing because of:
```
2022-10-26T13:59:46.5941995Z [ERROR] testOutboxEntityMetamodelExists  Time elapsed: 0.005 s  <<< ERROR!
2022-10-26T13:59:46.5942782Z java.lang.RuntimeException: java.lang.NoSuchMethodError: 'void org.jboss.jandex.Indexer.index(java.io.InputStream)'
2022-10-26T13:59:46.5943752Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:625)
2022-10-26T13:59:46.5944897Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:696)
2022-10-26T13:59:46.5948225Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
2022-10-26T13:59:46.5949247Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2022-10-26T13:59:46.5950371Z 	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
2022-10-26T13:59:46.5951472Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
2022-10-26T13:59:46.5953362Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2022-10-26T13:59:46.5954458Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2022-10-26T13:59:46.5955682Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2022-10-26T13:59:46.5956677Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2022-10-26T13:59:46.5957742Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
2022-10-26T13:59:46.5959168Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)
2022-10-26T13:59:46.5960185Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
2022-10-26T13:59:46.5961442Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
2022-10-26T13:59:46.5962376Z 	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
2022-10-26T13:59:46.5963400Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
2022-10-26T13:59:46.5964438Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
```
- Operator SDK test is failing because of:
```
2022-10-26T14:02:12.3198751Z [ERROR] io.quarkiverse.operatorsdk.it.OperatorSDKResourceTest  Time elapsed: 22.645 s  <<< ERROR!
2022-10-26T14:02:12.3200207Z java.lang.RuntimeException: 
2022-10-26T14:02:12.3201496Z java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2022-10-26T14:02:12.3204611Z 	[error]: Build step io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor#createConfigurationServiceAndOperator threw an exception: java.lang.NoSuchMethodError: 'java.lang.Object io.fabric8.kubernetes.client.dsl.NonNamespaceOperation.createOrReplace(java.lang.Object[])'
2022-10-26T14:02:12.3206946Z 	at io.quarkiverse.operatorsdk.runtime.CRDUtils.apply(CRDUtils.java:48)
2022-10-26T14:02:12.3271841Z 	at io.quarkiverse.operatorsdk.runtime.CRDUtils.lambda$applyCRD$0(CRDUtils.java:29)
2022-10-26T14:02:12.3272469Z 	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
2022-10-26T14:02:12.3273056Z 	at io.quarkiverse.operatorsdk.runtime.CRDUtils.applyCRD(CRDUtils.java:24)
2022-10-26T14:02:12.3274053Z 	at io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor.createConfigurationServiceAndOperator(OperatorSDKProcessor.java:236)
2022-10-26T14:02:12.3275041Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-26T14:02:12.3275787Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-10-26T14:02:12.3276600Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-10-26T14:02:12.3277280Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-10-26T14:02:12.3277842Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
2022-10-26T14:02:12.3278405Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
2022-10-26T14:02:12.3279185Z 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2022-10-26T14:02:12.3279799Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-10-26T14:02:12.3280479Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-10-26T14:02:12.3281019Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-26T14:02:12.3281491Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

So one of the issue is that we don't enforce the old Jandex version in the quarkus-bom anymore so Jandex is actually downgraded to 2.4.0.Final where it's used.

As for the Operator SDK issue, it's probably an issue with the new Kubernetes Client and we will need an upgrade.

**Comment by gsmet** [comment]
Note that this is for your awareness so that you know that this needs a fix when Quarkus Core 2.14.0.Final core artifacts will be available.
Here it's just the CR1.

**Comment by metacosm** [comment]
For the operator SDK extension, I was waiting for this release to be able to merge the changes needed (which currently live in the `next` branch) as the extension wouldn't even build without this Quarkus release otherwise.

**Comment by Naros** [comment]
Hi @gsmet, I'll give a look. Should I send any extension changes in a separate PR and you'll rebase here?

**Comment by aloubyansky** [comment]
I'm afraid @metacosm is right here @gsmet. It looks like either we release a shrunk platform in CR1 or we don't release the platform at all until all the members upgrade to quarkus-bom 2.14.0.CR1.

**Comment by metacosm** [comment]
QOSDK main branch is now switched to use 2.14.0.CR1 so things should be fixed for the Java Operator SDK extension now.

**Comment by aloubyansky** [comment]
Could you release a CR @metacosm to integrate into the platform (branch)?

**Comment by metacosm** [comment]
> Could you release a CR @metacosm to integrate into the platform (branch)?

I was afraid you'd say that 😉 
Would a beta be good enough? I don't have much feedback on this version as it's quite literally the first time it builds out of the box so labelling it CR feels a little presumptuous…

**Comment by Naros** [comment]
Hi @aloubyansky @gsmet, I'll check with my project lead to see when we can cut a new release of Debezium.  We just cut 2.0.0.Final last week and we normally operate on a 3-week cadence, but I'll see if we can potentially cut a 2.0.1.Final earlier to satisfy the Quarkus platform release.

**Comment by aloubyansky** [comment]
Normally we'd release the final version in a week but given the situation we should probably give more time for the members to adjust @gsmet?

**Comment by Naros** [comment]
Hi @aloubyansky @gsmet so when I used 2.14.CR1, we got the following error in one of our tests:
```
[error]: Build step io.quarkus.vertx.http.deployment.VertxHttpProcessor#bodyHandler threw an exception: java.lang.IllegalAccessError: failed to access class io.netty.util.internal.logging.MessageFormatter from class io.quarkus.netty.deployment.JBossNettyLoggerFactory$JBossNettyInternalLogger (io.netty.util.internal.logging.MessageFormatter and io.quarkus.netty.deployment.JBossNettyLoggerFactory$JBossNettyInternalLogger are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @7c2b6087)
```
Now I tested upgrading from 2.11.0.Final to 2.12.0.Final, 2.13.0.Final, and 2.13.3.Final and all of those upgrades went smoothly.  Can either of you point me to what could be causing this problem?

**Comment by metacosm** [comment]
> Normally we'd release the final version in a week but given the situation we should probably give more time for the members to adjust @gsmet?

The problem, at least in the case of the QOSDK extension, is that there's a sort of cyclic dependency: the extension cannot be released before the appropriate Fabric8 Kubernetes Client version is available in Quarkus. Since the client updatea tend to be merged relatively late in the release cycle, this makes it complicated to make any sort of progress on the QOSDK extension in the mean time but then the platform now depends on the extension being released as well so 🤷🏼… Not sure what's the best way to proceed here, actually…

**Comment by Ladicek** [comment]
Looking at the stack traces [above](https://github.com/quarkusio/quarkus-platform/pull/673#issuecomment-1292138132):

The Camel issue (`org.jboss.jandex.MethodParameterInfo cannot be cast to class org.jboss.jandex.Type`) can be worked around using `MethodInfo.args()`, that works on all Jandex versions (by accident, the method is deprecated and I didn't pay attention to it :-) ).

The Debezium issue (`NoSuchMethodError: 'void org.jboss.jandex.Indexer.index(java.io.InputStream)'`) looks like something was compiled against Jandex 3 and then ran against Jandex 2, not sure what exactly. Maybe there's Jandex 2 sneaking in transitively and an exclusion somewhere might help?

**Comment by Ladicek** [comment]
Also, if anyone has a Jandex-related problem, please ping me anytime (in European working hours :-) ) and I'll be glad to help.

**Comment by metacosm** [comment]
QOSDK 5.0.0.Beta1 has been released and should be used in this PR.

**Comment by gsmet** [comment]
I disabled the Camel Quarkus tests and Debezium tests for CR1 and will proceed with the release.

**Comment by gsmet** [comment]
@Naros so as for DBZ, once Quarkus core 2.14.0.Final is released, we would need an updated DBZ extension based on Quarkus 2.14.0.Final and using the new Jandex artifact i.e. `io.smallrye:jandex`, ideally, you would let the Quarkus BOM enforce the version.

**Comment by Naros** [comment]
Understand @gsmet, that shouldn't be a problem.

**Pull request merged**
