### PR TITLE
Adding supported extensions for 1.11

### PR DESCRIPTION
**Pull request by harshmadhani**
Adding supported extensions for 1.11 cc @tqvarnst

### CODE REVIEW

**Comment by gsmet** [comment]
I relaunched CI as one of the job failed because of a CI error.

**Comment by gsmet** [comment]
I will release 1.11.2.Final tomorrow so it would be nice if we could get your approval before 2pm tomorrow @tqvarnst .

**Comment by gsmet** [comment]
OK, well, I will merge this and you can tweak things in the product later on if need be.

**Comment by harshmadhani** [comment]
Thanks @gsmet !

**Pull request merged**
