### PR TITLE
 Enable batch mode to avoid a too verbose output

### PR DESCRIPTION
**Pull request by geoand**
Same as https://github.com/quarkusio/quarkus-ecosystem-ci/pull/14

### CODE REVIEW

**Comment by ppalaga** [comment]
`-ntp` is another good candidate https://maven.apache.org/docs/3.6.1/release-notes.html#user-visible-changes

**Comment by geoand** [comment]
Ah, nice!

**Comment by geoand** [comment]
It seems like `-B` is a superset of `-ntp`, no?

**Comment by ppalaga** [comment]
> It seems like `-B` is a superset of `-ntp`, no?

I think `-B` there is still a lot of `Download[ing|ed] <url>` lines in the log that are not there with `-ntp`

**Comment by geoand** [comment]
I'll check tomorrow morning after the job has run.

If I see those entries, I'll add `-ntp` as well

**Pull request merged**
