### PR TITLE
Kogito 1.19.0.Final + OptaPlanner 8.19.0.Final

### PR DESCRIPTION
**Pull request by mbiarnes**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by radtriste** [comment]
```
(pool-2-thread-1) Creating container for image: confluentinc/cp-kafka:5.4.3
2022-03-17T16:07:19.0362990Z 2022-03-17 16:07:19,035 INFO  [🐳 .4.3]] (pool-2-thread-1) Container confluentinc/cp-kafka:5.4.3 is starting: 21367fac044b55b4f20785e3e0d64cfb1934b9d7dd9ba17a575343206650855d
2022-03-17T16:07:19.5246779Z /var/lib/redpanda/redpanda.sh: line 2: /usr/bin/rpk: No such file or directory
2022-03-17T16:07:19.5314825Z 2022-03-17 16:07:19,530 INFO  [org.kie.kog.tes.KogitoGenericContainer] (docker-java-stream--350982928) STDERR: /var/lib/redpanda/redpanda.sh: line 2: /usr/bin/rpk: No such file or directory
2022-03-17T16:08:19.4667749Z 2022-03-17 16:08:19,461 ERROR [🐳 .4.3]] (pool-2-thread-1) Could not start container: java.lang.IllegalStateException: Container exited with code 127
```
@evacchi didn't we migrate to redpanda containers ?
@aloubyansky could it be that there is an override of the kafka container somehow ?

**Comment by aloubyansky** [comment]
It could be overridden with `quarkus.kafka.devservices.image-name` but I am not sure whether it actually is in this case.
https://quarkus.io/guides/kafka-dev-services#configuring-the-image

**Comment by evacchi** [comment]
> @evacchi didn't we migrate to redpanda containers ?

AFAIK @cristianonicolai did @radtriste (FYI @tiagodolphine)

**Comment by radtriste** [comment]
oh wait this seems a problem with the pom.xml in the platform ... we need to update it 
```
<container.image.kafka>vectorized/redpanda:v21.11.8</container.image.kafka>
```

**Comment by radtriste** [comment]
update is coming

**Comment by tiagodolphine** [comment]
> > @evacchi didn't we migrate to redpanda containers ?
> 
> AFAIK @cristianonicolai did @radtriste (FYI @tiagodolphine)

yeah, seems the root cause is somehow confluentinc/cp-kafka was used instead of redpanda, and KogitoKafkaContainer is now specific / coupled to redpanda.

**Comment by radtriste** [comment]
@mbiarnes please merge @michalszynkiewicz

**Comment by gsmet** [comment]
I rebased and squashed the commits.

**Review by gsmet — APPROVED** [review]

**Pull request merged**
