### PR TITLE
Use Debezium BOM

### PR DESCRIPTION
**Pull request by Naros**
Hi @aloubyansky, hopefully this conforms to what Quarkus wants when providing the BOMs.  Let me know if I need to adjust anything so this can be merged for this week's platform release.  Thanks!

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
Looks good @Naros However, I just noticed https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L60 doesn't seem to be used anywhere. Should it be removed or is something missing?

**Comment by Naros** [comment]
I do think that should be removed since pulling in the {{debezium-outbox}} implies a certain Debezium version anyway since they're both released together.  I'll add a commit that removes that momentarily.

**Comment by aloubyansky** [comment]
@Naros we've just merged Kogito and OptaPlanner upgrades and that created conflicts with your PR. Could you please rebase your changes? You could also squash the commits. Thanks a lot!

**Comment by aloubyansky** [comment]
You can simply remove and re-generate the generated-platform-project.

**Comment by Naros** [comment]
Sure thing @aloubyansky, give me a few minutes and I'll take care of that for you.

**Comment by Naros** [comment]
After doing this @aloubyansky, I noticed that the following files make reference to the Oracle Instant Client:
```
        modified:   generated-platform-project/quarkus-camel/bom/pom.xml
        modified:   generated-platform-project/quarkus-kogito/descriptor/pom.xml
        modified:   generated-platform-project/quarkus-kogito/properties/src/main/resources/platform-properties.properties
        modified:   generated-platform-project/quarkus-optaplanner/descriptor/pom.xml
        modified:   generated-platform-project/quarkus-optaplanner/properties/src/main/resources/platform-properties.properties
        modified:   generated-platform-project/quarkus-universe/bom/pom.xml
```
This dependency is marked as provided by the Debezium Oracle connector, should these files not define this as provided too?

**Comment by gsmet** [comment]
@Naros they are BOMs so they just define the version, nothing more.

**Comment by aloubyansky** [comment]
It's actually generally a good practice to not specify scopes in BOMs.

**Comment by Naros** [comment]
Ah; thanks guys.  Not a Maven expert so I appreciate the insight!

**Pull request merged**
