### PR TITLE
Upgrade to Debezium 2.2.0.Final

### PR DESCRIPTION
**Pull request by Naros**
@gsmet I added the new reactive component along side the existing non-reactive Debezium outbox component.  Is this done correctly or do I need to make changes here?

### CODE REVIEW

**Comment by gsmet** [comment]
@aloubyansky could you have a look?

**Comment by aloubyansky** [comment]
Is there a reason to keep it separate? Could we add the reactive extension to the existing Debezium config?

**Review by aloubyansky — CHANGES_REQUESTED** [review]
It needs a re-config either way.

**Comment by Naros** [comment]
> Is there a reason to keep it separate? Could we add the reactive extension to the existing Debezium config?

I'm sorry @aloubyansky I don't quite follow.  I merely kept a single `<member>` definition in the Platform pom.xml, are you asking that the contents of the upstream artifacts be merged somehow and if so, can you elaborate?

**Comment by aloubyansky** [comment]
Here is what I see
```
                                <member>
                                    <name>Debezium-Outbox</name>
                                    <dependencyManagement>
                                        <dependency>io.debezium:debezium-quarkus-outbox:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-quarkus-outbox-deployment:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-api:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-cassandra:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-db2:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-mongodb:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-mysql:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-oracle:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-postgres:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-sqlserver:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-vitess:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-core:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-ddl-parser:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-embedded:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-scripting:${debezium-quarkus-outbox.version}</dependency>
                                    </dependencyManagement>
                                    <release>
                                        <lastDetectedBomUpdate>io.quarkus.platform:quarkus-debezium-bom:2.14.0.CR1</lastDetectedBomUpdate>
                                        <next>${platform.groupId}:quarkus-debezium-bom:${platform.version}</next>
                                    </release>
                                    <tests>
                                        <test>
                                            <skip>false</skip>
                                            <artifact>io.debezium:debezium-quarkus-outbox-integration-tests:${debezium-quarkus-outbox.version}</artifact>
                                        </test>
                                        <test>
                                            <skip>false</skip>
                                            <artifact>io.debezium:debezium-quarkus-outbox-reactive-integration-tests:${debezium-quarkus-outbox.version}</artifact>
                                        </test>
                                    </tests>
                                </member>
                                <member>
                                    <name>Debezium-Outbox Reactive</name>
                                    <dependencyManagement>
                                        <dependency>io.debezium:debezium-quarkus-outbox-reactive:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-quarkus-outbox-reactive-deployment:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-api:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-cassandra:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-db2:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-mongodb:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-mysql:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-oracle:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-postgres:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-sqlserver:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-vitess:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-core:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-ddl-parser:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-embedded:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-scripting:${debezium-quarkus-outbox.version}</dependency>
                                    </dependencyManagement>
                                    <release>
                                        <lastDetectedBomUpdate>io.quarkus.platform:quarkus-debezium-bom:2.14.0.CR1</lastDetectedBomUpdate>
                                        <next>${platform.groupId}:quarkus-debezium-bom:${platform.version}</next>
                                    </release>
                                    <tests>
                                        <test>
                                            <skip>false</skip>
                                            <artifact>io.debezium:debezium-quarkus-outbox-reactive-integration-tests:${debezium-quarkus-outbox.version}</artifact>
                                        </test>
                                    </tests>
                                </member>
```
Could we add the reactive extension to the existing Debezium member?

**Comment by aloubyansky** [comment]
In addition to that both members use the same `${platform.groupId}:quarkus-debezium-bom` for the result.

**Comment by Naros** [comment]
So remove the `Debezium-Outbox Reactive`, and combine the two members as this:
```
                                <member>
                                    <name>Debezium-Outbox</name>
                                    <dependencyManagement>
                                        <dependency>io.debezium:debezium-quarkus-outbox:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-quarkus-outbox-deployment:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-quarkus-outbox-reactive:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-quarkus-outbox-reactive-deployment:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-api:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-cassandra:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-db2:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-mongodb:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-mysql:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-oracle:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-postgres:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-sqlserver:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-connector-vitess:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-core:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-ddl-parser:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-embedded:${debezium-quarkus-outbox.version}</dependency>
                                        <dependency>io.debezium:debezium-scripting:${debezium-quarkus-outbox.version}</dependency>
                                    </dependencyManagement>
                                    <release>
                                        <lastDetectedBomUpdate>io.quarkus.platform:quarkus-debezium-bom:2.14.0.CR1</lastDetectedBomUpdate>
                                        <next>${platform.groupId}:quarkus-debezium-bom:${platform.version}</next>
                                    </release>
                                    <tests>
                                        <test>
                                            <skip>false</skip>
                                            <artifact>io.debezium:debezium-quarkus-outbox-integration-tests:${debezium-quarkus-outbox.version}</artifact>
                                        </test>
                                        <test>
                                            <skip>false</skip>
                                            <artifact>io.debezium:debezium-quarkus-outbox-reactive-integration-tests:${debezium-quarkus-outbox.version}</artifact>
                                        </test>
                                    </tests>
                                </member>
```
Does that look acceptable @aloubyansky ?

**Comment by aloubyansky** [comment]
That's what I would expect, yes. Thanks.

**Comment by Naros** [comment]
@gsmet looks like we just stepped on one another, sorry.

**Comment by gsmet** [comment]
Yes I was fixing things on my side. I think you pushed it without syncing and I fixed it. But apparently you force pushed again after me, hopefully with the fix :).

I will let you do your things if you're on it.

**Comment by gsmet** [comment]
There is still a problem with the project generation on your side. Let me take care of it, please.

**Comment by gsmet** [comment]
I pushed something that should be good.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
