### PR TITLE
Kogito 1.9.0.Final + OptaPlanner 8.9.0.Final

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by aloubyansky** [comment]
Thanks @radtriste Could you please run `mvn process-resources` locally and include all the changes to the `generated-platform-project`? The first build will take some time.

**Comment by radtriste** [comment]
sure will do.
Should it be done each time ? if yes, then I could update our script

**Comment by aloubyansky** [comment]
Yes, it should be done for every PR. Until we do that from a github action automatically or something. Thanks!

**Comment by radtriste** [comment]
@aloubyansky This is done

**Review by aloubyansky — APPROVED** [review]
Looks good, thanks @radtriste !

**Pull request merged**
