### PR TITLE
Skip kogito-quarkus-integration-test until the API incompatibility is fixed

### PR DESCRIPTION
**Pull request by aloubyansky**

### CODE REVIEW

**Comment by gsmet** [comment]
@aloubyansky is it something we can improve in Core somehow?

**Comment by aloubyansky** [comment]
Well, see https://github.com/quarkusio/quarkus/issues/8593#issuecomment-986509428

**Comment by aloubyansky** [comment]
BTW, i am not sure why the check has failed. It's clean locally. Did we switch to Maven 3.8.4 in the platform?

**Comment by gsmet** [comment]
@aloubyansky it failed in setup-java, no worries.

**Pull request merged**
