### PR TITLE
Kogito: Re-enable predictions test

### PR DESCRIPTION
**Pull request by radtriste**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by aloubyansky** [comment]
Thanks @radtriste I'm re-running the tests.

**Comment by radtriste** [comment]
@aloubyansky @gsmet could we merge that one for 2.15 ?
I have https://github.com/quarkusio/quarkus-platform/pull/723 to be ready by Monday and I would like this change to be included if possible ...

**Comment by radtriste** [comment]
or I include those changes in https://github.com/quarkusio/quarkus-platform/pull/723 directly ...

**Review by aloubyansky — APPROVED** [review]

**Comment by radtriste** [comment]
Still issues after rebase ...

**Comment by radtriste** [comment]
will rebase that one once https://github.com/quarkusio/quarkus-platform/pull/723 is merged. That latter one is more urgent

**Comment by radtriste** [comment]
@gsmet @aloubyansky good to be merged :)

**Pull request merged**
