### PR TITLE
Bump Kogito to 0.13.0

### PR DESCRIPTION
**Pull request by evacchi**

### CODE REVIEW

**Comment by evacchi** [comment]
`quarkus-universe-integration-tests-camel-rpkgtests` failed. I am confused

**Comment by gsmet** [comment]
I restarted CI.

**Comment by gsmet** [comment]
I force pushed a rebase on top of the 1.7.0.CR2 upgrade. Let's see what CI says.

**Comment by gsmet** [comment]
Yeah I know, don't worry.

**Comment by gsmet** [comment]
I merged that one even if we are waiting for 0.13.1.

**Pull request merged**
