### PR TITLE
Upgrade OptaPlanner from 7.39.0.Final to 7.41.0.Final

### PR DESCRIPTION
**Pull request by rsynek**
Please see also https://github.com/quarkusio/quarkus-quickstarts/pull/637

### CODE REVIEW

**Comment by gsmet** [comment]
Hi @rsynek ,

Thanks for this. Just to be sure, did you coordinate with @ge0ffrey ?

**Comment by rsynek** [comment]
Hi, @gsmet! Yes, @ge0ffrey asked me to update the version. 7.41.0.Final is the latest one released.

**Comment by gsmet** [comment]
Perfect, thanks! Let's merge then.

**Comment by rsynek** [comment]
@gsmet thank you. Could you kindly also have a look at the related https://github.com/quarkusio/quarkus-quickstarts/pull/637 ?

**Pull request merged**
