### PR TITLE
Add Google Cloud Services to the platform

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes https://github.com/quarkusio/quarkus/issues/16175

@aloubyansky I try to mvn install the platform locally and it didn't goes to the end, it do run the Google Cloud Services IT without issue but fail inside the Camel IT.

### CODE REVIEW

**Comment by aloubyansky** [comment]
It doesn't look like these artifacts are available yet?
````
Warning:  The POM for io.quarkiverse.googlecloudservices:quarkus-google-cloud-services-main-it:jar:0.8.0.CR1 is missing, no dependency information available
Warning:  The POM for io.quarkiverse.googlecloudservices:quarkus-google-cloud-services-main-it:jar:tests:0.8.0.CR1 is missing, no dependency information available
````

Let's see the failure. FYI @ppalaga

**Comment by aloubyansky** [comment]
@loicmathieu when you open a PR, could you please run `mvn process-resources` and add the changes to the generated project too? It makes the changes to the other member BOMs visible in the PR. Thanks.

**Comment by loicmathieu** [comment]
> It doesn't look like these artifacts are available yet?

I had a failure in my release action but saw the artifacts was deployed ... in fact the integration test one are missing :( I'll have a look.

> could you please run mvn process-resources and add the changes to the generated project too

I was not sure I'll need to push all changes so I only included the one for the platform BOM. I'll update my PR.

**Comment by aloubyansky** [comment]
Thanks, now we can see how Camel is affected.

**Comment by ppalaga** [comment]
The failure is still in quarkus-google-cloud-services-main-it, isn't it?

**Comment by aloubyansky** [comment]
yes, the test jars aren't available in central https://repo1.maven.org/maven2/io/quarkiverse/googlecloudservices/

**Comment by aloubyansky** [comment]
It passed. False alarm?

**Comment by aloubyansky** [comment]
````
2021-06-22T09:28:53.8281814Z [INFO] Quarkus Platform - GoogleCloudServices - Quarkus Platform BOM SUCCESS [  0.018 s]
2021-06-22T09:28:53.8282902Z [INFO] Quarkus Platform - GoogleCloudServices - Parent .... SUCCESS [  0.039 s]
2021-06-22T09:28:53.8284009Z [INFO] Quarkus Platform - GoogleCloudServices - Integration Tests - Parent SUCCESS [  0.025 s]
2021-06-22T09:28:53.8286453Z [INFO] Quarkus Platform - GoogleCloudServices - Integration Tests - quarkus-google-cloud-services-main-it SUCCESS [01:20 min]
2021-06-22T09:28:53.8290723Z [INFO] Quarkus Platform - GoogleCloudServices - Quarkus Platform Descriptor SUCCESS [  0.099 s]
2021-06-22T09:28:53.8292128Z [INFO] Quarkus Platform - GoogleCloudServices - Quarkus Platform Properties SUCCESS [  0.022 s]
````
And all the Camel tests.

**Review by aloubyansky — APPROVED** [review]

**Comment by loicmathieu** [comment]
@aloubyansky I finally successfully publish the IT test jar :)
And yeah! It works !!!
So now, I'm inside the Platform :tada:

**Comment by aloubyansky** [comment]
Congrats @loicmathieu, great work!

**Comment by ppalaga** [comment]
Welcome on board @loicmathieu !

**Pull request merged**
