### PR TITLE
Migrate to GitHub actions

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
Kogito fails which according to @gsmet is to be expected for now

**Comment by maxandersen** [comment]
@geoand anything blocking this for going in ?

**Comment by geoand** [comment]
I totally forgot about this one...

Let me rebase

**Comment by geoand** [comment]
Force pushed an update

**Comment by gsmet** [comment]
So I would like us to be consistent and use GH Actions everywhere. My only issue is that when doing a release, I don't want to be blocked by the queue being full of Quarkus Core CI builds.

We don't have a way to keep a few jobs free for important tasks with GH Actions so I wonder if we should wait for having a proper solution before doing the switch.

**Comment by gsmet** [comment]
@geoand I just refreshed and improved this PR as we have more and more issues with Azure. Even if it might be a bit of pain to cancel already planned jobs to get this tested when releasing, it will still be better than having our builds failing.

I'll see how the CI build goes.

**Comment by geoand** [comment]
Cool, I had forgot about this completely :)

**Pull request merged**
