### PR TITLE
Revert Downgrade angus-mail to 1.1.0

### PR DESCRIPTION
**Pull request by ppalaga**
fix https://github.com/quarkiverse/quarkus-cxf/issues/899

### CODE REVIEW

**Comment by ppalaga** [comment]
This may not be a regression, because there is (strangely) no change in the generated BOMs.

**Comment by aloubyansky** [comment]
It's because the CEQ BOM includes 2.0.2 version of it and it wins during alignment.

**Comment by ppalaga** [comment]
Is this good to merge in spite of the CI failures?

**Review by gsmet — APPROVED** [review]
Yes, we can merge.

Both failing components need a new release to be compatible with 3.3.

**Pull request merged**
