### PR TITLE
Upgrade to camel-quarkus 1.0.0-M1

### PR DESCRIPTION
**Pull request by ppalaga**
@lburgazzoli could you please have a look at the `core-main` test in the native mode? 8/8 tests are failing there without any apparent cause. I am out of ideas.

Everything else works as expected.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@ppalaga guess we can skip this and upgrade to 1.0.0-M2 directly

**Comment by lburgazzoli** [comment]
@ppalaga I think you need to skip tests tagged with "quarkus-platform-ignore" also on failsafe, currently they are skipped only by surefire (as far as I can see)

**Comment by ppalaga** [comment]
> you need to skip tests tagged with "quarkus-platform-ignore" also on failsafe

Yes, that helped to eliminate one of the failing tests, but the remaining 7 are still failing.

I just noticed that the `staging` config profile is not picked when starting the native test app. 

The command executed by `NativeImageLauncher` correctly contains `-Dquarkus.profile=staging` but the app then logs `Profile prod activated` anyway. 

@aloubyansky do you happen to have any idea how to make the native app accept the `staging` profile?

Here is the complete log:

```
[INFO] Running org.apache.camel.quarkus.core.CamelITCase
Executing [/home/ppalaga/orgs/quarkus/quarkus-platform/integration-tests/camel-core-main/target/quarkus-universe-integration-tests-camel-core-main-999-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log, -Dquarkus.profile=staging]
2019-12-18 11:32:04,403 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Using properties from classpath:application.properties
2019-12-18 11:32:04,404 WARN  [org.apa.cam.mai.BaseMainSupport] (main) configurer = null
2019-12-18 11:32:04,405 WARN  [org.apa.cam.mai.BaseMainSupport] (main) configurer = null
2019-12-18 11:32:04,405 WARN  [org.apa.cam.mai.BaseMainSupport] (main) configurer = null
2019-12-18 11:32:04,406 INFO  [org.apa.cam.mai.DefaultRoutesCollector] (main) Loading additional Camel XML routes from: classpath:my-routes.xml
2019-12-18 11:32:04,406 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Apache Camel 3.0.0 (CamelContext: quarkus-camel-example) is starting
2019-12-18 11:32:04,406 INFO  [org.apa.cam.imp.eng.DefaultManagementStrategy] (main) JMX is disabled
2019-12-18 11:32:04,406 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2019-12-18 11:32:04,407 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Using ReactiveExecutor: org.apache.camel.reactive.vertx.VertXReactiveExecutor@7fabf2015918
2019-12-18 11:32:04,407 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Route: beforeStart started and consuming from: timer://beforeStart
2019-12-18 11:32:04,407 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Route: configure started and consuming from: timer://configure
2019-12-18 11:32:04,407 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Total 2 routes, of which 2 are started
2019-12-18 11:32:04,407 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Apache Camel 3.0.0 (CamelContext: quarkus-camel-example) started in 0.001 seconds
2019-12-18 11:32:04,407 INFO  [io.quarkus] (main) quarkus-universe-integration-tests-camel-core-main 999-SNAPSHOT (running on Quarkus 1.0.1.Final) started in 0.010s. Listening on: http://0.0.0.0:8081
2019-12-18 11:32:04,407 INFO  [io.quarkus] (main) Profile prod activated. 
2019-12-18 11:32:04,407 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-direct, camel-log, camel-main-support, camel-reactive-executor, camel-support-common, camel-support-xml, camel-timer, camel-xml, cdi, resteasy-jsonb, vertx]
2019-12-18 11:32:05,407 INFO  [beforeStart] (vert.x-eventloop-thread-2) Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]
2019-12-18 11:32:05,407 INFO  [configure] (vert.x-eventloop-thread-6) Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]
[ERROR] Tests run: 7, Failures: 7, Errors: 0, Skipped: 0, Time elapsed: 1.669 s <<< FAILURE! - in org.apache.camel.quarkus.core.CamelITCase
```

**Comment by lburgazzoli** [comment]
I think you just need to copy what we have on our tests: https://github.com/apache/camel-quarkus/blob/master/integration-tests/core-main/pom.xml#L133

**Comment by ppalaga** [comment]
> I think you just need to copy what we have on our tests: https://github.com/apache/camel-quarkus/blob/master/integration-tests/core-main/pom.xml#L133

It is already there, and that's why the `NativeImageLauncher` sees it.

**Comment by aloubyansky** [comment]
There is a bug/limitation at the moment, system props are not propagated to the native image test unless provided by `QuarkusTestResourceLifecycleManager`. We discussed some time ago with @lburgazzoli

**Comment by lburgazzoli** [comment]
yes but some properties are taken into account like `quarkus.test.native-image-profile` is propagated to the native image as `-Dquarkus.profile=...` but it looks like it is not taken into account

**Comment by ppalaga** [comment]
Yes, it is probably the native image that is causing the issue. 

Some observations:

The image in the camel-quarkus build tree has 72M, but here just 65M. I wonder if such a big difference is expected?

Both binaries return a match when being grepped for `staging.the.message` (a string from application.properties). Changing some entries in application.properties behaves as expected, so the application sees the right application.properties file.

The application returns 404 when the tests are hitting the http endpoints. Let me try to add some logging to figure out what is happening.

**Comment by ppalaga** [comment]
When comparing the `target/*native-image-source-jar` directories between here and camel-quarkus, i can see some classes missing here in `target/*native-image-source-jar/*-runner.jar`. E.g. `org/apache/camel/quarkus/core/CamelServlet.class` is missing here. That's a class from the test application responsible for serving the HTTP endpoints. Is that expected @aloubyansky ?

`target/*native-image-source-jar/lib` here an there contain the same number of jars.

**Comment by aloubyansky** [comment]
When did it start failing? It used to pass, right?

**Comment by ppalaga** [comment]
It is working now. I had to remove `src/main/resources/application.properties` that I added to experiment with application.properties.

So the existence of `src/main/resources/application.properties` seems to cause that the classes of the test app are not copied to `target/*native-image-source-jar/*-runner.jar`. I am not sure whether it is a bug or an expected behavior.

**Comment by ppalaga** [comment]
This PR is good to merge from ma PoV.

@lburgazzoli I'd prefer to merge this one and I'd start working on an upgrade to camel-quarkus 1.0.0-M2 straight away. WDYT?

**Comment by lburgazzoli** [comment]
fine with me

**Comment by ppalaga** [comment]
Is this good to merge, @aloubyansky ?

**Comment by maxandersen** [comment]
replaced with https://github.com/quarkusio/quarkus-platform/pull/19

**Pull request closed without merging**
