### PR TITLE
Upgrade to Camel Quarkus 3.0.0-RC1

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
0fd8c22:

* Rebased
* Excluded the failing test https://github.com/apache/camel-quarkus/issues/5086

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
I suppose this is to be backported to 3.2 @ppalaga?

**Comment by ppalaga** [comment]
> I suppose this is to be backported to 3.2 @ppalaga?

Ups, sorry, I did not know there was a separate 3.2 branch. Yes, I'd very much like this to become a part of 3.2.1.Final. 
Should I send a separate PR for 3.2?

**Comment by aloubyansky** [comment]
That'd be appreciated @ppalaga Thanks!

**Comment by ppalaga** [comment]
> That'd be appreciated @ppalaga Thanks!

Thanks, done: https://github.com/quarkusio/quarkus-platform/pull/893

**Pull request merged**
