### PR TITLE
[3.2] Update QOSDK to 6.3.3

### PR DESCRIPTION
**Pull request by metacosm**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by metacosm** [comment]
Not sure what this needs, I did run `./mvnw -Dsync` before opening the PR (and did so again, just now, to double check), and there isn't any more changes to commit.

**Comment by aloubyansky** [comment]
It's because you have the Gradle Maven repo enabled in your settings while it's not enabled in the CI and most of our local configs, it results in gradle-tooling-api added to the quarkus-bom.

**Comment by metacosm** [comment]
Hmm, I don't recall doing anything specific. I'm not even sure what this "Gradle Maven repo" is supposed to refer to, to be honest… What do I need to do to fix the issue?

**Comment by aloubyansky** [comment]
It seems like you have https://repo.gradle.org/artifactory/libs-releases or a mirror of it enabled in your settings. If you disable it it should fix the check.

**Comment by metacosm** [comment]
I don't, though. `cat ~/.m2/settings.xml | grep gradle` returns nothing. Or if I do, I have no idea where it is and I certainly didn't set it up.

**Comment by metacosm** [comment]
Of note, I've opened several similar PRs with the exact same configuration without issue before so I don't know why this would failing now.

**Comment by aloubyansky** [comment]
And if you re-sync it it's still the same?

**Comment by metacosm** [comment]
> And if you re-sync it it's still the same?

yes

**Comment by metacosm** [comment]
Hmm, that said, the PR was opened by a bot, so it probably has different settings than I do. That said, this also isn't the first PR opened by the bot either so 🤷🏼

**Pull request merged**
