### PR TITLE
Updating JSON file to include jdbc-oracle support

### PR DESCRIPTION
**Pull request by harshmadhani**

### CODE REVIEW

**Comment by harshmadhani** [comment]
cc @maxandersen

**Comment by maxandersen** [comment]
@ia3andy can you confirm this matches what you expect ?

i  believe its fine to merge but just want to check you dont see any issue with committign it before code.quarkus.redhat.com is ready?

**Comment by ia3andy** [comment]
@maxandersen looking good.. this will not be backported to 1.11 right?

**Comment by geoand** [comment]
Is this good to backport to 2.2?

**Comment by maxandersen** [comment]
Yes. Just 2.2 and onwards. So yes should be back ported to 2.2.3

**Pull request merged**
