### PR TITLE
[3.8] Upgrade Quarkus CXF to 3.8.5 & Camel Quarkus to 3.8.3

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Comment by ppalaga** [comment]
Looks great, thanks @jamesnetherton!

**Comment by gsmet** [comment]
@ppalaga do we need the OpenTelemetry Semconv status before merging this one? If not, we could merge but there is a small conflict to fix.

**Comment by ppalaga** [comment]
> do we need the OpenTelemetry Semconv status before merging this one?

Nope, this is Quarkus CXF 3.8.5 using the older CXF 4.0.4, where the OpenTelemetry Semconv problem is not present. 

I'd like to release Quarkus CXF 3.8.6 using CXF 4.0.5, that fixes two CVEs and brings the compat problem with OpenTelemetry Semconv

**Comment by jamesnetherton** [comment]
I fixed up the conflict to get the PR back into a mergeable state.

**Comment by gsmet** [comment]
@ppalaga I merged this one to be safe. Let's follow up on 3.8.6 next.

**Pull request merged**
