### PR TITLE
Fix lowercase in category description

### PR DESCRIPTION
**Pull request by gastaldi**
`s/KAfka/Kafka`

### CODE REVIEW

**Comment by gsmet** [comment]
You need to run `./mvnw -Dsync` after your changes.

**Comment by gastaldi** [comment]
Ah, so the warning when opening the PR is real, gotcha! 😉

**Comment by gastaldi** [comment]
Hm, the change is now gone. Where should I perform that change?

**Comment by gastaldi** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/25111

**Pull request closed without merging**
