### PR TITLE
Upgrade to Camel Quarkus 2.2.0

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
Ouch, this will fail, because the artifacts were not synced to Central yet. Sorry, I should have waited.

**Comment by gsmet** [comment]
Is it for Quarkus 2.2? Are you aware that the release is today? I can probably wait a couple of hours but not much more.

Please force push when the artifacts are synced to Central. Thanks!

**Review by aloubyansky — APPROVED** [review]

**Comment by ppalaga** [comment]
> Is it for Quarkus 2.2? Are you aware that the release is today? I can probably wait a couple of hours but not much more.

I released the staging repo around 8:00, I hope the artifacts will land in Central soon. Sorry for the inconvenience.

**Comment by ppalaga** [comment]
Some of the artifacts are there already, so the sync is in progress. Just need to wait till it is complete.

**Comment by ppalaga** [comment]
I force-pushed, all Camel Quarkus artifacts are in Central now.

**Comment by gsmet** [comment]
OK, I will push the 2.2.1 upgrade here too so that I'm sure we don't have conflicts.

**Comment by ppalaga** [comment]
The CI passed.

**Pull request merged**
