### PR TITLE
Exclude org.testcontainers dependencies from the BOM

### PR DESCRIPTION
**Pull request by aloubyansky**
This PR removes the testcontainers dependencies from the BOM.
/cc @evacchi @mariofusco

### CODE REVIEW

**Comment by evacchi** [comment]
@aloubyansky that should be fixed in my pr for kogito 1.0

**Comment by gsmet** [comment]
@aloubyansky I think this should be merged anyway, right?

**Comment by aloubyansky** [comment]
> @aloubyansky I think this should be merged anyway, right?

It could be, yes. We probably don't want this coming from any where.

**Comment by evacchi** [comment]
No problem, just FYI

**Review by evacchi — APPROVED** [review]

**Pull request merged**
