### PR TITLE
Update Blaze-Persistence to 1.6.4

### PR DESCRIPTION
**Pull request by beikov**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@aloubyansky the check failed with a NPE:
```
Error:  Failed to execute goal io.quarkus:quarkus-platform-bom-maven-plugin:0.0.45:generate-platform-descriptor (default) on project quarkus-universe-bom-quarkus-platform-descriptor: Execution default of goal io.quarkus:quarkus-platform-bom-maven-plugin:0.0.45:generate-platform-descriptor failed. NullPointerException -> [Help 1]
7397
Error:  
7398
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
7399
Error:  Re-run Maven using the -X switch to enable full debug logging.
7400
Error:  
7401
Error:  For more information about the errors and possible solutions, please read the following articles:
7402
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
7403
Error:  
7404
Error:  After correcting the problems, you can resume the build with the command
7405
Error:    mvn <args> -rf :quarkus-universe-bom-quarkus-platform-descriptor
```

We should probably try to launch it again with -e.

**Comment by beikov** [comment]
I suppose the error is not due to my changes and you will take care of this?

**Comment by aloubyansky** [comment]
It is due to your changes, of course, but we'll take care of it :) I'll need to reproduce it locally.

**Comment by aloubyansky** [comment]
Yes @gsmet, we should add `-e` to the command. I couldn't reproduce it locally.

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
And you needed me for that? ;)

I just did it, let's see what CI has to say!

**Comment by gsmet** [comment]
Error is:
```
Caused by: java.lang.NullPointerException
    at io.quarkus.bom.decomposer.maven.GeneratePlatformDescriptorJsonMojo.extensionId (GeneratePlatformDescriptorJsonMojo.java:682)
    at io.quarkus.bom.decomposer.maven.GeneratePlatformDescriptorJsonMojo.execute (GeneratePlatformDescriptorJsonMojo.java:389)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
```

**Comment by gsmet** [comment]
This is the culprit:
```
    private String extensionId(Extension extObject) {
        return extObject.getArtifact().getGroupId() + ":" + extObject.getArtifact().getArtifactId();
    }
```
so somehow either `extObject` or `extObject.getArtifact()` is null.

**Comment by aloubyansky** [comment]
I was confused originally, I thought the "check" was running `-Dsync` but it's actually `./mvnw -B clean process-resources --settings .github/mvn-settings.xml -e` and it fails of the descriptor generation. This is reproducible locally.

**Comment by aloubyansky** [comment]
The reason is that the `META-INF/quarkus-extension.yaml` in `blaze-persistence-integration-quarkus-1.6.4.jar` is missing some elements, `artifact` is one of them, it's also missing e.g. `built-with-quarkus-core`, which is pretty important for the tools. Looking at the 1.6.3 version of it, the YAML file is using the older structure. The missing elements are typically generated by the `quarkus-bootstrap-maven-plugin:extension-descriptor` but I don't see it being configured for https://github.com/Blazebit/blaze-persistence/blob/master/integration/quarkus/runtime/pom.xml, so we just get https://github.com/Blazebit/blaze-persistence/blob/master/integration/quarkus/runtime/src/main/resources/META-INF/quarkus-extension.yaml

**Comment by aloubyansky** [comment]
With https://github.com/quarkusio/quarkus-platform-bom-generator/pull/104 it will fail with the following message
````
[ERROR] Failed to execute goal io.quarkus:quarkus-platform-bom-maven-plugin:0.0.46-SNAPSHOT:generate-platform-descriptor (default) on project quarkus-universe-bom-quarkus-platform-descriptor: META-INF/quarkus-extension.yaml of com.blazebit:blaze-persistence-integration-quarkus:jar:1.6.4 is missing the artifact coordinates, please make sure the extension metadata is complete -> [Help 1]
````

**Comment by gsmet** [comment]
Closing this one. We will have to wait for the next Blaze Persistence release.

**Pull request closed without merging**
