### PR TITLE
Use Quarkus 2.0-compatible version of Quarkus Hazelcast Client

### PR DESCRIPTION
**Pull request by pivovarit**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by aloubyansky** [comment]
@pivovarit could you please run `mvn process-resources` and include the changes to the `generated-platform-project` too?

**Comment by pivovarit** [comment]
Ok, let me figure out how to do that!

**Comment by aloubyansky** [comment]
It'll take a bit of time unfortunately for the first build. Subsequent builds would be ~15 sec. It helps evaluate the actual changes in the dependency constraints of all the platform members.

**Comment by aloubyansky** [comment]
Perhaps will look into automating it in the future.

**Comment by aloubyansky** [comment]
BTW, the title implies the previous version is incompatible. Could you please clarify what the issues were? The tests would pass for the previous version.

**Comment by pivovarit** [comment]
There was one minor issue with native compilation on MacOS, but to be honest I did not pay that much attention to the wording. I'd be fine renaming the PR to "Quarkus 2.0-based version of (...)"

**Comment by aloubyansky** [comment]
That's ok, thanks for the info and the upgrade!

**Comment by pivovarit** [comment]
@aloubyansky do I need to commit generated files and that's all?

**Comment by aloubyansky** [comment]
yes, please

**Comment by pivovarit** [comment]
@aloubyansky I think it's done

**Comment by aloubyansky** [comment]
Awesome. I really like your extension @pivovarit I wish we had more like yours :)

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
I will backport it to the 2.0 branch once merged.

**Pull request merged**
