### PR TITLE
Update to Quarkus 2.2.4.Final

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
Tests are failing with:
```2021-12-15 10:48:20,206 INFO  [org.apa.cam.qua.com.geo.it.GeocoderNominationResource] (executor-thread-0) Retrieve info from georgraphic coordinates latitude : 40.714224, longitude -73.961452
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.471 s <<< FAILURE! - in org.apache.camel.quarkus.component.geocoder.it.GeocoderNominationTest
Error:  loadLatLong  Time elapsed: 0.966 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
JSON path city doesn't match.
Expected: New York
  Actual: New York City
```

/cc @ppalaga @jamesnetherton 
I will disable this test in 2.2

**Comment by gsmet** [comment]
I also disabled `camel-quarkus-integration-test-js-dsl` due to:

> java.lang.AbstractMethodError: Receiver class com.oracle.truffle.polyglot.PolyglotEngineDispatch does not define or inherit an implementation of the resolved method 'abstract org.graalvm.polyglot.Context createContext(java.lang.Object, java.io.OutputStream, java.io.OutputStream, java.io.InputStream, boolean, org.graalvm.polyglot.HostAccess, org.graalvm.polyglot.PolyglotAccess, boolean, boolean, boolean, boolean, boolean, java.util.function.Predicate, java.util.Map, java.util.Map, java.lang.String[], org.graalvm.polyglot.io.FileSystem, java.lang.Object, boolean, org.graalvm.polyglot.io.ProcessHandler, org.graalvm.polyglot.EnvironmentAccess, java.util.Map, java.time.ZoneId, java.lang.Object, java.lang.String, java.lang.ClassLoader, boolean)' of abstract class org.graalvm.polyglot.impl.AbstractPolyglotImpl$AbstractEngineDispatch.

**Comment by ppalaga** [comment]
> Tests are failing with:
> 
> ```
> Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.471 s <<< FAILURE! - in org.apache.camel.quarkus.component.geocoder.it.GeocoderNominationTest
> Error:  loadLatLong  Time elapsed: 0.966 s  <<< FAILURE!
> java.lang.AssertionError: 
> 1 expectation failed.
> JSON path city doesn't match.
> Expected: New York
>   Actual: New York City
> ```

Nice to see that you test with a real Google cloud account! We have not seen this because we are mocking the responses. I have filed https://github.com/apache/camel-quarkus/issues/3389 Thanks for the notice!

**Comment by gsmet** [comment]
@ppalaga well, I didn't do anything specific for testing. I wonder if we are missing the mocked responses and thus the requests are done. I know we had some issues with having to copy some resources. /cc @aloubyansky

**Comment by ppalaga** [comment]
> I also disabled `camel-quarkus-integration-test-js-dsl` due to:
> 
> > java.lang.AbstractMethodError: Receiver class com.oracle.truffle.polyglot.PolyglotEngineDispatch does not define or inherit an implementation of the resolved method 'abstract org.graalvm.polyglot.Context createContext(java.lang.Object, java.io.OutputStream, java.io.OutputStream, java.io.InputStream, boolean, org.graalvm.polyglot.HostAccess, org.graalvm.polyglot.PolyglotAccess, boolean, boolean, boolean, boolean, boolean, java.util.function.Predicate, java.util.Map, java.util.Map, java.lang.String[], org.graalvm.polyglot.io.FileSystem, java.lang.Object, boolean, org.graalvm.polyglot.io.ProcessHandler, org.graalvm.polyglot.EnvironmentAccess, java.util.Map, java.time.ZoneId, java.lang.Object, java.lang.String, java.lang.ClassLoader, boolean)' of abstract class org.graalvm.polyglot.impl.AbstractPolyglotImpl$AbstractEngineDispatch.

Sounds after a GraalVM upgrade. Filed https://github.com/apache/camel-quarkus/issues/3390

**Comment by gsmet** [comment]
@ppalaga yes exactly. I was asked to upgrade GraalVM to 21.3 for 2.2. We haven't foreseen the problems with Camel. We should probably set up a workflow to test these things.

**Comment by ppalaga** [comment]
> @ppalaga well, I didn't do anything specific for testing. I wonder if we are missing the mocked responses and thus the requests are done. I know we had some issues with having to copy some resources. /cc @aloubyansky

You must be testing with `GOOGLE_API_KEY` env var set and it is definitely a good thing! Otherwise you would not hit this.

**Comment by gsmet** [comment]
@ppalaga I don't think that's it because I don't see GitHub Actions defining a key (and we don't) and I also had the issue with `camel-quarkus-integration-test-xchange` service being unresponsive.

I will merge anyway.

**Pull request merged**
