### PR TITLE
[QUARKUS-406] fix MRRC url

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
@gsmet I cannot add labels, this needs to go to 1.7 too

**Comment by michalszynkiewicz** [comment]
@ia3andy also cannot add reviewers ;)

**Review by ia3andy — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
We don't have a backport policy for the platform.

So basically, ping @geoand and I and we'll do the backport.

**Comment by gsmet** [comment]
And @ia3andy did you use a merge commit? Because not using them makes backporting harder, the commit in the PR is not the one merged.

**Comment by ia3andy** [comment]
@gsmet I think I didn't :-/

**Pull request merged**
