### PR TITLE
kogito 1.26.0.Final

### PR DESCRIPTION
**Pull request by mbiarnes**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by radtriste** [comment]
@gsmet @aloubyansky to you for merging

**Comment by aloubyansky** [comment]
@radtriste thanks! Would you mind squashing the commits?

**Comment by radtriste** [comment]
@mbiarnes  ?

**Comment by mbiarnes** [comment]
@radtriste squashed

**Comment by aloubyansky** [comment]
@loicmathieu fyi, we seem to have a recurrent failure in `io.quarkiverse.googlecloudservices.it.BigtableResourceTest.testBigtable` Will you have time to look into it? Thanks.

**Comment by loicmathieu** [comment]
@aloubyansky it's stange as this one never failed locally nor when launched inside the extension CI.
Is there a way to launch the "platform test" locally to have a look?

**Comment by aloubyansky** [comment]
Yes, sure
1. `mvn clean package -DskipTests`
2. cd into the test module you want to test and `mvn clean test` or whatever arguments you need to test

**Comment by aloubyansky** [comment]
It passed this time @loicmathieu So possibly not easy to reproduce locally. That was the 3rd attempt though.

**Pull request merged**
