### PR TITLE
Upgrade to Quarkus CXF 2.3.0

### PR DESCRIPTION
**Pull request by ppalaga**
Quarkus CXF 2.2.1 was built aganst Quarkus 3.2.4. Let's see if it's going to work with Quarkus 3.3.0.RC1

### CODE REVIEW

**Comment by ppalaga** [comment]
OK, I'll have to prepare a different release for Quarkus 3.3.0. This one for 3.2 is good to merge though: https://github.com/quarkusio/quarkus-platform/pull/927

**Comment by ppalaga** [comment]
>  I'll have to prepare a different release for Quarkus 3.3.0

I tested locally, that recompiling QCXF against Quarkus 3.3 solves the CXF related test failures. I'd release QCXF once Quarkus Core 3.3.0 is available.

**Comment by gsmet** [comment]
@ppalaga I merged 3.3.0, I let you release and update CXF? Thanks!

**Comment by ppalaga** [comment]
aeb7236: Quarkus CXF 2.3.0 that was compiled against Quarkus 3.3.0

**Review by gsmet — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Pull request merged**
