### PR TITLE
[2.16] Update to Quarkus Qpid JMS 0.45.0

### PR DESCRIPTION
**Pull request by gemmellr**
Update to Quarkus Qpid JMS 0.45.0, uses Qpid JMS 1.10.0 against Quarkus 2.16.7.Final

### CODE REVIEW

**Comment by gemmellr** [comment]
I think most of the camel test failures are due to the brokers they are using blocking producers due to e.g the disk space usage, and so tests aren't receiving expected messages. There are for example lots of logs like:

>2023-06-30T12:31:35.4531229Z 2023-06-30 12:31:35,451 WARN  [org.apa.act.art.cor.client] (executor-thread-0) AMQ212054: Destination address=mapTest is blocked. If the system is configured to block make sure you consume messages on this configuration.
2023-06-30T12:31:45.4534533Z 2023-06-30 12:31:45,452 WARN  [org.apa.act.art.cor.client] (executor-thread-0) AMQ212054: Destination address=mapTest is blocked. If the system is configured to block make sure you consume messages on this configuration.
...
2023-06-30T12:32:55.4858937Z 2023-06-30 12:32:55,485 WARN  [org.apa.act.art.cor.client] (executor-thread-1) AMQ212054: Destination address=objectTest is blocked. If the system is configured to block make sure you consume messages on this configuration.
2023-06-30T12:32:55.5150779Z 2023-06-30 12:32:55,514 WARN  [org.apa.act.art.cor.client] (executor-thread-2) AMQ212054: Destination address=txTest is blocked. If the system is configured to block make sure you consume messages on this configuration.
...
2023-06-30T12:33:05.5154669Z 2023-06-30 12:33:05,514 WARN  [org.apa.act.art.cor.client] (executor-thread-2) AMQ212054: Destination address=txTest is blocked. If the system is configured to block make sure you consume messages on this configuration.
2023-06-30T12:33:05.5486111Z 2023-06-30 12:33:05,548 WARN  [org.apa.act.art.cor.client] (executor-thread-3) AMQ212054: Destination address=selectorA is blocked. If the system is configured to block make sure you consume messages on this configuration.
...

and also more explicitly:

> 2023-06-30T12:57:26.5075268Z 2023-06-30 12:57:26,505 WARN  [org.apache.activemq.artemis.core.server] AMQ222212: Disk Full! Blocking message production on address 'pojoProduce'. Clients will report blocked.

Some of the other non-camel tests were already failing on previous 2.16 runs before this PR, again it seems complaining about disk space, eg:

> 2023-06-30T13:34:55.0234925Z Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/lib/google-cloud-sdk/bin/local-extract: no space left on device

**Comment by aloubyansky** [comment]
FYI @jamesnetherton @ppalaga @zbendhiba

**Comment by aloubyansky** [comment]
@gemmellr is it related to the changes in this PR?

**Comment by gemmellr** [comment]
For the record, there were no code changes in the newer the qpid-jms client itself, only dependency update in the form of newer Netty, which is actually overridden by quarkus-qpid-jms with whatever quarkus uses; as the same version of quarkus was used as the prior extension, the dependencies actually also shouldnt have changed.

**Comment by gemmellr** [comment]
@aloubyansky Doesnt seem like it. The run before this showed the run was running out of disk space, this seems like it just happened earlier.

I dont see how it could be related anyway really, this PR should be basically a noop currently since the quarkus bom actually governs our dependency versions except the JMS API jar and the client itself..which as I say, the same quarkus version was used as before, and there were no code changes in the client.

**Review by aloubyansky — APPROVED** [review]

**Comment by gemmellr** [comment]
FWIW, here is a modified build run from my fork with my PR changes included, but then modified to just run the above failing camel tests, when they then all pass:
https://github.com/gemmellr/quarkus-platform/actions/runs/5443086933

The google-cloud-services tests were already failing before this PR, e.g the prior run on 2.16 branch for PR https://github.com/quarkusio/quarkus-platform/pull/867

(Which actually I see now was in fact partly about disabling some other JMS tests using Artemis, seemingly as some failed on PR #864 for the same disk use reason they have on this run. The Camel tests are using the default Artemis config where the broker blocks producers when the journal disk is > 90% full, which it has become in these runs. The tests could configure Artemis to e.g disable the disk space usage check so they werent affected until its entirely full instead [which is what seems to be happening to the google-cloud-services tests]).

**Comment by gsmet** [comment]
I'm trying to improve the situation here: https://github.com/quarkusio/quarkus-platform/pull/881

**Comment by gsmet** [comment]
I cherry picked the fix for the disk space and pushed it to your PR, let's see how it goes.

**Comment by gemmellr** [comment]
Great. Should go about the same as it would without this essentially non-change hehe.

**Pull request merged**
