### PR TITLE
[3.15] Update Quarkus Amazon Services to 2.18.1

### PR DESCRIPTION
**Pull request by scrocquesel**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by scrocquesel** [comment]
Let me know if we need to backport this PR on 3.14

**Comment by aloubyansky** [comment]
I don't think so, 3.15.0 should be released next Wednesday. Upgrading the version in main would be good though. Thanks!

**Comment by scrocquesel** [comment]
I haven't release the extension with 3.15 PR merged. I will update with 2.18 when done.

**Comment by scrocquesel** [comment]
@gastaldi Since https://github.com/quarkiverse/quarkus-amazon-services/pull/1392, I got this when running `./mvnw -Dsync`

```
[WARNING] The POM for io.quarkiverse.amazonservices:quarkus-amazon-services-integration-tests:pom:2.18.0 is missing, no dependency information available
```

**Comment by scrocquesel** [comment]
> @gastaldi Since [quarkiverse/quarkus-amazon-services#1392](https://github.com/quarkiverse/quarkus-amazon-services/pull/1392), I got this when running `./mvnw -Dsync`
> 
> ```
> [WARNING] The POM for io.quarkiverse.amazonservices:quarkus-amazon-services-integration-tests:pom:2.18.0 is missing, no dependency information available
> ```

I revert part of the PR to publish the integration-test module

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
