### PR TITLE
Update to Quarkus Qpid JMS 2.1.0

### PR DESCRIPTION
**Pull request by gemmellr**
Update to Quarkus Qpid JMS 2.1.0, uses Qpid JMS 2.2.0 against Quarkus 3.0.1.Final

### CODE REVIEW

**Comment by gemmellr** [comment]
Seperately, can this be introduced to the 3.0.x platform? Its the same Qpid JMS client version as used before, we only added an option to the extension itself (disabled by default, so behaviour is unchanged from before unless asked) to enable it to allow [quarkus-pooled-jms](https://github.com/quarkiverse/quarkus-pooled-jms) to supply pooling for the injected ConnectionFactory.

Similarly...if released, could an newer extension version for Quarkus 2.16.x adding this be introduced to the 2.16.x platform?

**Comment by aloubyansky** [comment]
> Seperately, can this be introduced to the 3.0.x platform?

Sure, that's what the `main` branch is currently.

For 2.16, I am not sure cherry-picking will work but you could open a PR against `2.16` branch @gemmellr

**Comment by gemmellr** [comment]
Ah ok, I thought further 3.0.x releases would come from the 3.0 branch rather than main.

This wont cherry-pick to 2.16, it needs a different extension version which I haven't released yet, for the older 'javax' client...was just enquiring before I do so I know whetehr to raise a PR (I'll release it either way though).

**Comment by aloubyansky** [comment]
Ah, sorry, I didn't realize Guillaume already created `3.0`. You're right, added the backport label. Thanks.

**Comment by gemmellr** [comment]
I raised #828 with the equivalent change (using Quarkus Qpid JMS 0.43.0) for the 2.16 branch.

I can raise another PR for 3.0 if needed...this one does cherry-pick there though.

**Comment by gemmellr** [comment]
@gsmet I see 3.0.2 was released..can I check the status on this? Hold for 3.1? Next 3.0.x? Needs PR?

**Comment by gsmet** [comment]
Hmmm, sorry, I totally missed this discussion. Let me backport this.

**Pull request merged**
