### PR TITLE
Upgrade to Camel Quarkus 2.6.0

### PR DESCRIPTION
**Pull request by zbendhiba**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by zbendhiba** [comment]
I'm not aware about how the extensions are visible in the code.quarkus.io, and I'm wondering it there is something special to do to add the camel-jfr  ?

**Comment by zbendhiba** [comment]
The text for new features 
```
Camel 3.14
Camel 3.14 is the new LTS version of Camel. Compared to the previous LTS version (3.11), a lot of work has been done to bring new components, CamelJbang and Java 17 support. Improvements have been made to Core performance, Route configuration, and many components such as Kamelets and Kafka. For more details, check [Apache Camel 3.14 What’s New ](https://camel.apache.org/blog/2021/12/camel314-whatsnew/).

Camel JFR Native support
Camel JFR extension allows diagnosing Camel applications with Java Flight Recorder. The extension has been introduced in Camel Quarkus 1.7.0 with JVM support only. The extension is now fully supported in JVM mode and Native mode.
```

**Comment by gsmet** [comment]
Thanks @zbendhiba !

As for JFR, I see you removed the `unlisted: true` from the metadata so it will appear automatically on code.quarkus.io, nothing to do on your side.

**Review by gsmet — APPROVED** [review]
CI passed, let's merge! Thanks!

**Comment by zbendhiba** [comment]
Thanks @gsmet

**Pull request merged**
