### PR TITLE
Google Cloud services extension pack 1.0.0

### PR DESCRIPTION
**Pull request by loicmathieu**
When I launchd `mvn -Dsyn` it updates more than 200 pom with artifactid and groupId inverted !

I didn' commit all of them so I manually include only the changes made to version and new libraires on the 4 files that are usually udated when I update the platform for the Google Cloud services extensions.

As I may miss some changes in one of those 200 pom, maybe it would be better if someone can validate my PR locally (or just sync the platform after merging it).

Sorry for that :(

### CODE REVIEW

**Comment by aloubyansky** [comment]
@loicmathieu it's probably because you used `mvn` instead of the wrapper from the project.

**Comment by loicmathieu** [comment]
Well, I never use the wrapper ...

Let's wait for Monday so I can launch with the wrapper and be sure to catch all modifications.

**Comment by loicmathieu** [comment]
And looking at the CI status there is missing modifications.

**Comment by gsmet** [comment]
For the record: they changed how things were generated between two micro versions of Maven. That's why we use the wrapper now to make sure things stay consistent.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
