### PR TITLE
[2.7] Upgrade to Camel Quarkus 2.7.2

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
We wouldn't normally do a new 2.7 release unless there is a very good reason for it. E.g. @tqvarnst may have one. How urgent is this @ppalaga ?

**Comment by ppalaga** [comment]
> We wouldn't normally do a new 2.7 release unless there is a very good reason for it. E.g. @tqvarnst may have one. How urgent is this @ppalaga ?

Strange to hear that. I assumed Platform releases triggered by a participant's micro upgrade are no-brainers.
It is as urgent as wanting our end users use the newest 2.7 Camel Quarkus fixes we have just released.

**Comment by aloubyansky** [comment]
Are those fixes available in more recent versions? E.g. 2.9, 2.10?

**Comment by ppalaga** [comment]
> Are those fixes available in more recent versions? E.g. 2.9, 2.10?

Yes, but we advertise Camel Quarkus 2.7.x as LTS (long term support). It is based on a Quarkus LTS branch and a Camel LTS branch.

**Comment by aloubyansky** [comment]
This something we should coordinate on better.

**Pull request merged**
