### PR TITLE
Add a Camel dev mode test

### PR DESCRIPTION
**Pull request by ppalaga**
Let's have a simple manually maintained dev mode test for Camel Quarkus to prevent issues like https://github.com/apache/camel-quarkus/issues/1171

### CODE REVIEW

**Comment by ppalaga** [comment]
98f0c03 rebased to force restarting the CI.

**Comment by ppalaga** [comment]
efa227c rebased to force restarting the CI.

**Comment by ppalaga** [comment]
Strange that the dev mode test gets stuck on the CI although it is passing for me locally. Let me investigate tomorrow.

**Comment by ppalaga** [comment]
The test output suggests, that the execution is stuck somewhere between creating the test deployment app and invoking the test.

**Comment by ppalaga** [comment]
Reported https://github.com/quarkusio/quarkus/issues/9299

**Comment by ppalaga** [comment]
The CI is passing. Please review.

**Comment by ppalaga** [comment]
Could please somebody review this and merge if possible?

**Comment by gsmet** [comment]
Sorry for the delay.

**Comment by ppalaga** [comment]
Thanks, no problem.

**Pull request merged**
