### PR TITLE
Kogito 1.11.1.Final + OptaPlanner 8.11.1.Final

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Review by aloubyansky — CHANGES_REQUESTED** [review]
Contains staging repos that should be removed once the Kogito and OptaPlanner artifacts are in Maven Central.

**Comment by aloubyansky** [comment]
@mbiarnes next time you open a PR which you know is not ok to merge (like this one containing the staging repo), please clearly indicate that in the title and/or description. Thanks!

**Comment by mbiarnes** [comment]
@aloubyansky OK

**Comment by evacchi** [comment]
the build has failed because yesterday the artifacts weren't deployed yet. @mbiarnes can you force push again? or @aloubyansky can you restart?

**Comment by aloubyansky** [comment]
Sure, done @evacchi

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
