### PR TITLE
Update Blaze-Persistence to 1.6.2

### PR DESCRIPTION
**Pull request by beikov**

### CODE REVIEW

**Comment by aloubyansky** [comment]
@beikov is it meant to be backported to 2.2?

**Comment by beikov** [comment]
Yeah, sure. In fact it is still compatible with 1.x ;)

**Comment by aloubyansky** [comment]
Ok, thanks, it's just the main is 2.3 now.

**Comment by beikov** [comment]
Are you going to do the backports or do you need PRs for that?

**Comment by aloubyansky** [comment]
We are taking care of this @beikov, thanks.

**Pull request merged**
