### PR TITLE
Kogito 1.15.0.Final + OptaPlanner 8.15.0.Final

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by radtriste** [comment]
@aloubyansky @gsmet do we need to add the repo also in the maven-settings ?
as well, should [that](https://github.com/quarkusio/quarkus-platform/pull/397/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R241-R246) be set also ?

**Comment by aloubyansky** [comment]
Yes, AFAIR, that's what we concluded last time.

**Comment by radtriste** [comment]
update done

**Comment by radtriste** [comment]
not sure what is happening there:
```
2022-01-05T15:39:26.1387185Z applying codestarts...
2022-01-05T15:39:26.1388214Z 📚  java
2022-01-05T15:39:26.1389043Z 🔨  maven
2022-01-05T15:39:26.1389679Z 📦  quarkus
2022-01-05T15:39:26.1390403Z 📝  config-properties
2022-01-05T15:39:26.1393138Z 🔧  dockerfiles
2022-01-05T15:39:26.1393891Z 🔧  maven-wrapper
2022-01-05T15:39:26.1394661Z 🚀  kogito-dmn-codestart
2022-01-05T15:39:26.1641176Z [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 31.951 s <<< FAILURE! - in org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT
2022-01-05T15:39:26.1642529Z [ERROR] testContent  Time elapsed: 0.056 s  <<< FAILURE!
2022-01-05T15:39:26.1643118Z java.lang.AssertionError: 
2022-01-05T15:39:26.1644456Z [corresponding snapshot file not found for KogitoDMNCodeCodestartIT/testContent/src_test_java_ilove_quark_us_PricingTest.java (Use -Dsnap to create it automatically)] 
2022-01-05T15:39:26.1645428Z Expecting path:
2022-01-05T15:39:26.1646247Z   src/test/resources/__snapshots__/KogitoDMNCodeCodestartIT/testContent/src_test_java_ilove_quark_us_PricingTest.java
2022-01-05T15:39:26.1647105Z to exist (symbolic links were followed).
2022-01-05T15:39:26.1648576Z 	at org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT.testContent(KogitoDMNCodeCodestartIT.java:53)
2022-01-05T15:39:26.1649815Z 
2022-01-05T15:39:26.1900696Z 2022-01-05 15:39:26,189 INFO  [io.quarkus] (main) Quarkus stopped in 0.026s
2022-01-05T15:39:26.5381908Z [INFO] 
2022-01-05T15:39:26.5382733Z [INFO] Results:
2022-01-05T15:39:26.5383261Z [INFO] 
2022-01-05T15:39:26.5383770Z [ERROR] Failures: 
2022-01-05T15:39:26.5385905Z [ERROR]   KogitoDMNCodeCodestartIT.testContent:53 [corresponding snapshot file not found for KogitoDMNCodeCodestartIT/testContent/src_test_java_ilove_quark_us_PricingTest.java (Use -Dsnap to create it automatically)] 
2022-01-05T15:39:26.5387519Z Expecting path:
2022-01-05T15:39:26.5388834Z   src/test/resources/__snapshots__/KogitoDMNCodeCodestartIT/testContent/src_test_java_ilove_quark_us_PricingTest.java
2022-01-05T15:39:26.5389855Z to exist (symbolic links were followed).
2022-01-05T15:39:26.5390277Z [INFO] 
2022-01-05T15:39:26.5390745Z [ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by radtriste** [comment]
@mariofusco any idea ?

**Comment by radtriste** [comment]
is it related to `main` ? this test is ok on our side with Quarkus 2.6

**Comment by aloubyansky** [comment]
It might be looking for the resources on the filesystem instead of the classpath. These snapshot should be included in the test jar, I suppose. We may need a fix in the codestart testing for that.

**Comment by radtriste** [comment]
ok, so I should just ignore that test for now

**Comment by radtriste** [comment]
gonna make the change

**Comment by aloubyansky** [comment]
Yes, I'll debug it.

**Comment by gsmet** [comment]
@radtriste still failing:
```
Error:  Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 27.057 s <<< FAILURE! - in org.kie.kogito.it.InfinispanPersistenceIT
Error:  testPersistence  Time elapsed: 0.012 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.testcontainers.quarkus.InfinispanQuarkusTestResource@23367364
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.testcontainers.quarkus.InfinispanQuarkusTestResource@23367364
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: com.github.dockerjava.api.exception.BadRequestException: 
Status 400: {"message":"OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"-c\": executable file not found in $PATH: unknown"}
```

**Comment by gsmet** [comment]
@radtriste I'd like to release 2.6.2.Final on Monday latest so let's try to finalize this soon. Thanks.

**Comment by radtriste** [comment]
@gsmet weird error. And did not fail on our side... I will just disable that test for now

**Comment by radtriste** [comment]
@gsmet so at least the checks passed
Now waiting for the artifacts to be released. I hope to release them on Nexus by tomorrow. Then on Monday they should be available on Central...

**Comment by radtriste** [comment]
artifacts have been released to Nexus. Gonna update this PR

**Comment by radtriste** [comment]
to be merged once artifacts are available on Central :)

**Comment by gsmet** [comment]
I squashed the commits and rebased.

**Comment by gsmet** [comment]
Wouhou, CI is green, let's merge. Thanks @radtriste .

**Pull request merged**
