### PR TITLE
Upgrade to Quarkus 2.16.2.Final

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gemmellr** [comment]
Do you think the reflection registration changes from Quarkus main would ever be backported to 2.16.x? Should we backport #761 in case?

**Comment by gsmet** [comment]
I don't think we will backport anything breaking but let's be on the safe side. I will backport it once this is in (I don't want to interrupt CI or I won't be able to release today)

**Comment by gemmellr** [comment]
Great, thanks.

**Comment by gsmet** [comment]
Well... you got lucky... :)

**Comment by gsmet** [comment]
Well, the CI build failed so I had to restart it anyway. So I also pushed your changes.

**Pull request merged**
