### PR TITLE
[3.17] Upgrade to Quarkus CXF 3.17.3 and Camel Quarkus to 3.17.0

### PR DESCRIPTION
**Pull request by ppalaga**
This PR is for `3.17`. There is https://github.com/quarkusio/quarkus-platform/pull/1373 for `main`.

@zbendhiba feel free to cherry-pick this to your PR for 3.17 if this one is not merged yet on Monday.

### CODE REVIEW

**Comment by gsmet** [comment]
@ppalaga is the CI failure fixed with Camel Quarkus 3.17.0?

**Comment by gsmet** [comment]
I pushed the Camel Quarkus update here too to get a CI run of both and see if it fixes the failing test.

**Comment by zbendhiba** [comment]
I think I missed @ppalaga comment, unsure if I need to update something. Let's see how this latest build goes.

**Comment by gsmet** [comment]
Apparently CI is green so I would say we could merge.

**Comment by ppalaga** [comment]
This one looks great and can be merged. Thanks @zbendhiba and @gsmet !

**Comment by ppalaga** [comment]
> @ppalaga how about the other one #1373 ?
> 
> Are they the same PR ?

No,  #1373 aims `main`. This one is towards `3.17`. @gsmet likes it like that once the given Platform `.0` is out and the `x.y` branch has been forked.

**Comment by gsmet** [comment]
@zbendhiba to clarify the process, I grouped the PR as we had a CI failure and I wanted to check it would be fixed with the new Camel Quarkus version. If CI is happy, I'm perfectly fine merging these separately.

**Comment by gsmet** [comment]
@ppalaga I don't see any release notes available so I will let you add them to the upcoming blog post when you have them.

Ideally even better if I don't have to look for them :)

**Pull request merged**
