### PR TITLE
Update Cassandra client to 1.0.2

### PR DESCRIPTION
**Pull request by adutra**
This PR upgrades the Cassandra client for Quarkus 1.x to the latest version, published today.

### CODE REVIEW

**Comment by aloubyansky** [comment]
@adutra given that Cassandra is currently disabled (see https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L250) changing the version property won't really have any effect.
Once you have a release that's working with Quarkus 2.x (I wouldn't mind upgrading to 1.1.0-rc1, btw, just to try it out), in addition to updating the version property, please run `mvn clean process-resources` at least (this will re-generate the platform project) and add all the changes to the commit.

Changes to the root pom are actually enough for the build and release. But including the generated changes clearly shows the effects of the upgrades on the whole platform. Thanks!

**Comment by adutra** [comment]
@aloubyansky indeed the Cassandra extension is disabled on main currently. But this PR was intended for Quarkus 1.x only. Should I infer that it's not required anymore to provide extension updates for Quarkus 1.x?

**Comment by aloubyansky** [comment]
Oh, it's branch 1.13, sorry @adutra Makes sense.

**Comment by adutra** [comment]
No worries. Please don't merge right now, I'm going to bump the client to 1.0.3.

**Comment by aloubyansky** [comment]
I am not sure whether it's related to the upgrade but Camel is consistently failing. @ppalaga does this ring a bell?

````
[INFO] [INFO] Running org.apache.camel.quarkus.component.azure.storage.queue.it.AzureStorageQueueTest
[INFO] Downloading from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/apache/camel/quarkus/camel-quarkus-azure-storage-queue-deployment/1.8.1/camel-quarkus-azure-storage-queue-deployment-1.8.1.jar
[INFO] Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/apache/camel/quarkus/camel-quarkus-azure-storage-queue-deployment/1.8.1/camel-quarkus-azure-storage-queue-deployment-1.8.1.jar (7.3 kB at 25 kB/s)
[INFO] 2021-06-18 15:03:55,259 INFO  [org.apa.cam.qua.tes.moc.bac.MockBackendUtils] (pool-3-thread-1) Mock backend will be used
[INFO] 2021-06-18 15:03:55,299 INFO  [org.tes.doc.DockerClientProviderStrategy] (pool-3-thread-1) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
[INFO] 2021-06-18 15:03:55,656 INFO  [org.tes.doc.DockerClientProviderStrategy] (pool-3-thread-1) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
[INFO] 2021-06-18 15:03:55,657 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Docker host IP address is localhost
[INFO] 2021-06-18 15:03:55,698 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Connected to docker: 
[INFO]   Server Version: 20.10.6+azure
[INFO]   API Version: 1.41
[INFO]   Operating System: Ubuntu 18.04.5 LTS
[INFO]   Total Memory: 6954 MB
[INFO] 2021-06-18 15:03:55,701 INFO  [org.tes.uti.ImageNameSubstitutor] (pool-3-thread-1) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
[INFO] 2021-06-18 15:03:56,256 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
[INFO] 2021-06-18 15:03:56,256 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Checking the system...
[INFO] 2021-06-18 15:03:56,257 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) ✔︎ Docker server version should be at least 1.6.0
[INFO] 2021-06-18 15:03:56,344 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) ✔︎ Docker environment should have more than 2GB free disk space
[INFO] 2021-06-18 15:03:56,357 INFO  [🐳 .mic.com.10.0]] (pool-3-thread-1) Creating container for image: mcr.microsoft.com/azure-storage/azurite:3.10.0
[INFO] 2021-06-18 15:03:56,390 INFO  [🐳 .mic.com.10.0]] (pool-3-thread-1) Starting container with ID: f58e2c5f8f29f81156479df38401eb998e24da0f6d53861cc6fea1e7d65d094e
[INFO] 2021-06-18 15:03:56,754 INFO  [🐳 .mic.com.10.0]] (pool-3-thread-1) Container mcr.microsoft.com/azure-storage/azurite:3.10.0 is starting: f58e2c5f8f29f81156479df38401eb998e24da0f6d53861cc6fea1e7d65d094e
[INFO] 2021-06-18 15:03:57,303 INFO  [org.apa.cam.qua.tes.sup.azu.AzureStorageTestResource] (docker-java-stream-917278145) STDOUT: Azurite Blob service is starting at http://0.0.0.0:10000
[INFO] 2021-06-18 15:03:57,314 INFO  [org.apa.cam.qua.tes.sup.azu.AzureStorageTestResource] (docker-java-stream-917278145) STDOUT: Azurite Blob service is successfully listening at http://0.0.0.0:10000
[INFO] 2021-06-18 15:03:57,314 INFO  [org.apa.cam.qua.tes.sup.azu.AzureStorageTestResource] (docker-java-stream-917278145) STDOUT: Azurite Queue service is starting at http://0.0.0.0:10001
[INFO] 2021-06-18 15:03:57,320 INFO  [org.apa.cam.qua.tes.sup.azu.AzureStorageTestResource] (docker-java-stream-917278145) STDOUT: Azurite Queue service is successfully listening at http://0.0.0.0:10001
[INFO] 2021-06-18 15:03:57,965 INFO  [🐳 .mic.com.10.0]] (pool-3-thread-1) Container mcr.microsoft.com/azure-storage/azurite:3.10.0 started in PT1.621519S
[INFO] 2021-06-18 15:03:58,827 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
[INFO] 2021-06-18 15:03:58,883 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:0 started:0)
[INFO] 2021-06-18 15:03:58,884 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.9.0 (camel-1) started in 18ms (build:0ms init:13ms start:5ms)
[INFO] 2021-06-18 15:03:58,975 INFO  [io.quarkus] (main) Quarkus 1.13.7.Final on JVM started in 6.230s. Listening on: http://localhost:32979
[INFO] 2021-06-18 15:03:58,976 INFO  [io.quarkus] (main) Profile test activated. 
[INFO] 2021-06-18 15:03:58,976 INFO  [io.quarkus] (main) Installed features: [camel-azure-storage-queue, camel-core, camel-support-common, camel-support-jackson-dataformat-xml, camel-support-reactor-netty, cdi, micrometer, resteasy]
[INFO] 2021-06-18 15:04:00,500 INFO  [org.apa.cam.com.azu.sto.que.QueueComponent] (executor-thread-1) QueueServiceClient instance is already set at endpoint level: skipping the check in the registry
[INFO] 2021-06-18 15:04:00,684 INFO  [com.azu.sto.que.imp.Que.create] (parallel-1) --> PUT http://localhost:49178/devstoreaccount1//camel-quarkus-2f3a7073-549a-482e-a254-33bce2ec9c68(empty body)--> END PUT
[INFO] 2021-06-18 15:04:00,805 INFO  [org.apa.cam.qua.tes.sup.azu.AzureStorageTestResource] (docker-java-stream-917278145) STDOUT: 172.17.0.1 - - [18/Jun/2021:15:04:00 +0000] "PUT /devstoreaccount1//camel-quarkus-2f3a7073-549a-482e-a254-33bce2ec9c68 HTTP/1.1" 400 -
[INFO] 2021-06-18 15:04:00,814 INFO  [com.azu.sto.que.imp.Que.create] (reactor-http-epoll-1) <-- 400 http://localhost:49178/devstoreaccount1//camel-quarkus-2f3a7073-549a-482e-a254-33bce2ec9c68 (130 ms, unknown-length body)(body content not logged)<-- END HTTP
[INFO] 2021-06-18 15:04:00,880 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /azure-storage-queue/queue/create failed, error id: 53d87541-e030-47be-b801-ba30eb1ed924-1: org.jboss.resteasy.spi.UnhandledException: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
[INFO] 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
[INFO] 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[INFO] 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[INFO] 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
[INFO] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
[INFO] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
[INFO] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
[INFO] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[INFO] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[INFO] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[INFO] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[INFO] 	at java.base/java.lang.Thread.run(Thread.java:829)
[INFO] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[INFO] Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
[INFO] 	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
[INFO] 	at org.apache.camel.support.ExchangeHelper.extractResultBody(ExchangeHelper.java:696)
[INFO] 	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:591)
[INFO] 	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:587)
[INFO] 	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:189)
[INFO] 	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:195)
[INFO] 	at org.apache.camel.quarkus.component.azure.storage.queue.it.AzureStorageQueueResource.createQueue(AzureStorageQueueResource.java:82)
[INFO] 	at org.apache.camel.quarkus.component.azure.storage.queue.it.AzureStorageQueueResource_ClientProxy.createQueue(AzureStorageQueueResource_ClientProxy.zig:234)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO] 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO] 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[INFO] 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[INFO] 	... 15 more
[INFO] Caused by: com.azure.storage.queue.models.QueueStorageException: Status code 400, "<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
[INFO] <Error>
[INFO]   <Code>InvalidHeaderValue</Code>
[INFO]   <Message>The value for one of the HTTP headers is not in the correct format.
[INFO] RequestId:8f6f6ec7-2723-45f1-8cfa-314cebd75d0d
[INFO] Time:2021-06-18T15:04:00.794Z</Message>
[INFO]   <HeaderName>x-ms-version</HeaderName>
[INFO]   <HeaderValue>2020-08-04</HeaderValue>
[INFO] </Error>"
[INFO] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[INFO] 	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
[INFO] 	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378)
[INFO] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
[INFO] 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
[INFO] 	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
[INFO] 	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
[INFO] 	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
[INFO] 	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
[INFO] 	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
[INFO] 	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
[INFO] 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
[INFO] 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
[INFO] 	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
[INFO] 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
[INFO] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
[INFO] 	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
[INFO] 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
[INFO] 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
[INFO] 	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
[INFO] 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
[INFO] 	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
[INFO] 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
[INFO] 	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
[INFO] 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
[INFO] 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
[INFO] 	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:383)
[INFO] 	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
[INFO] 	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
[INFO] 	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
[INFO] 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
[INFO] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[INFO] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[INFO] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[INFO] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[INFO] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[INFO] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[INFO] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[INFO] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] 	at java.base/java.lang.Thread.run(Thread.java:829)
[INFO] 	Suppressed: java.lang.Exception: #block terminated with an error
[INFO] 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
[INFO] 		at reactor.core.publisher.Mono.block(Mono.java:1685)
[INFO] 		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:131)
[INFO] 		at com.azure.storage.queue.QueueClient.createWithResponse(QueueClient.java:135)
[INFO] 		at org.apache.camel.component.azure.storage.queue.client.QueueClientWrapper.create(QueueClientWrapper.java:44)
[INFO] 		at org.apache.camel.component.azure.storage.queue.operations.QueueOperations.createQueue(QueueOperations.java:56)
[INFO] 		at org.apache.camel.component.azure.storage.queue.QueueProducer.process(QueueProducer.java:59)
[INFO] 		at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
[INFO] 		at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:217)
[INFO] 		at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111)
[INFO] 		at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
[INFO] 		at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108)
[INFO] 		at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:190)
[INFO] 		at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
[INFO] 		at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
[INFO] 		at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:153)
[INFO] 		at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:187)
[INFO] 		at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:195)
[INFO] 		at org.apache.camel.quarkus.component.azure.storage.queue.it.AzureStorageQueueResource.createQueue(AzureStorageQueueResource.java:82)
[INFO] 		at org.apache.camel.quarkus.component.azure.storage.queue.it.AzureStorageQueueResource_ClientProxy.createQueue(AzureStorageQueueResource_ClientProxy.zig:234)
[INFO] 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO] 		at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO] 		at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[INFO] 		at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[INFO] 		at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[INFO] 		at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[INFO] 		at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] 		at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[INFO] 		at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[INFO] 		at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
[INFO] 		at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
[INFO] 		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[INFO] 		at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[INFO] 		at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[INFO] 		at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] 		at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[INFO] 		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[INFO] 		at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
[INFO] 		at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
[INFO] 		at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
[INFO] 		at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
[INFO] 		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[INFO] 		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[INFO] 		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[INFO] 		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[INFO] 		at java.base/java.lang.Thread.run(Thread.java:829)
[INFO] 		at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[INFO] 
Error: [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.737 s <<< FAILURE! - in org.apache.camel.quarkus.component.azure.storage.queue.it.AzureStorageQueueTest
Error: [ERROR] crud  Time elapsed: 2.117 s  <<< FAILURE!
[INFO] java.lang.AssertionError: 
[INFO] 1 expectation failed.
[INFO] Expected status code <201> but was <500>.
````

**Comment by ppalaga** [comment]
The `AzureStorageQueueTest` is passing for me locally in 1.13 branch both before and after this change. Hard to say why it is failing here. I am quite sure it is unrelated to the current change. Feel free to disable this test and perhaps also other camel azure tests if they fail in this branch.

**Comment by gsmet** [comment]
Closing this one, there won't be any more 1.x.

**Pull request closed without merging**
