### PR TITLE
Add blaze-persistence

### PR DESCRIPTION
**Pull request by Mobe91**

### CODE REVIEW

**Comment by gsmet** [comment]
I asked @beikov and @Mobe91 to fix the description of the extension as it's displaying "Blaze Persistence Parent" on code.quarkus.io.

We should have an update soon.

**Comment by Mobe91** [comment]
@gsmet The Azure pipeline error looks weird, could you please try to restart the pipeline? I don't have permission to do so,,

**Comment by aloubyansky** [comment]
@gsmet is on pto. I've restarted your the CI.

**Comment by gsmet** [comment]
I rebased and force-pushed to fix a conflict. Will merge as soon as CI is green.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
