### PR TITLE
Kogito 1.14.1.Final + OptaPlanner 8.14.1.Final

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by radtriste** [comment]
@evacchi any idea here ?

**Comment by evacchi** [comment]
failure seems related to @ia3andy's issue with the codestart /cc FYI @tarilabs

**Comment by tarilabs** [comment]
meaning is there an upstream quarkus issue to track please?

**Comment by aloubyansky** [comment]
You may need to propagate the `maven.settings` in the platform test too.

**Comment by aloubyansky** [comment]
It was fixed in 2.5.1.Final https://github.com/quarkusio/quarkus/pull/21673

**Comment by aloubyansky** [comment]
@radtriste could you apply the change?

**Comment by aloubyansky** [comment]
Didn't help it seems. I'll check what's going on.

**Comment by radtriste** [comment]
did it. but FYI, Kogito artifacts have been released already, so this should not be needed anymore. But good to know for the next time ;)

**Comment by gsmet** [comment]
I'm releasing Quarkus 2.5.2.Final tomorrow morning early Paris time so if you want this in, we need the staging repo gone and the PR rebased and regenerated with `./mvw -Dsync`. I'm not sure there will be a 2.5.3.Final.

**Comment by gsmet** [comment]
Given the late time, I will do it and see how it goes.

**Comment by gsmet** [comment]
The artifacts are not available yet unfortunately.

**Comment by gsmet** [comment]
Platform release will probably be around 2pm so I'll check tomorrow morning. I think it's going to be a pain to rebase so I will rebase it this evening.

**Comment by gsmet** [comment]
It will conflict with https://github.com/quarkusio/quarkus-platform/pull/402 so I will rebase it once the other PR is merged.

**Comment by gsmet** [comment]
I just force pushed a rebase on top of latest 2.5.

**Comment by aloubyansky** [comment]
BTW, it'd be better to use `$$` for the properties instead of `$` to avoid revealing actual paths on your local machines. E.g.
````
<maven.settings>$${session.request.userSettingsFile.path}</maven.settings>
````
instead of
````
<maven.settings>${session.request.userSettingsFile.path}</maven.settings>
````

**Comment by aloubyansky** [comment]
The artifacts still aren't in Central. But I could make progress with these changes:

````
diff --git a/.github/mvn-settings.xml b/.github/mvn-settings.xml
index d5e4664b..66ae9b04 100644
--- a/.github/mvn-settings.xml
+++ b/.github/mvn-settings.xml
@@ -14,6 +14,14 @@
             <enabled>false</enabled>
           </snapshots>
         </repository>
+        <repository>
+            <snapshots>
+                <enabled>false</enabled>
+            </snapshots>
+            <id>kogito</id>
+            <name>kogito</name>
+            <url>https://repository.jboss.org/nexus/content/groups/kogito-public/</url>
+        </repository>

diff --git a/pom.xml b/pom.xml
index 401525a5..f6a46b24 100644
--- a/pom.xml
+++ b/pom.xml
@@ -66,8 +66,8 @@
         <quarkus-blaze-persistence.version>1.6.3</quarkus-blaze-persistence.version>
         <quarkus-cassandra-client.version>1.1.1</quarkus-cassandra-client.version>
 
-        <kogito-quarkus.version>1.14.0.Final</kogito-quarkus.version>
-        <optaplanner-quarkus.version>8.14.0.Final</optaplanner-quarkus.version>
+        <kogito-quarkus.version>1.14.1.Final</kogito-quarkus.version>
+        <optaplanner-quarkus.version>8.14.1.Final</optaplanner-quarkus.version>
 
         <quarkus-google-cloud-services.version>0.11.0</quarkus-google-cloud-services.version>
 
@@ -238,6 +238,14 @@
                                         <container.image.infinispan>infinispan/server:12.1.4.Final</container.image.infinispan>
                                         <container.image.kafka>confluentinc/cp-kafka:5.4.3</container.image.kafka>
                                         <container.image.keycloak>jboss/keycloak:14.0.0</container.image.keycloak>
+
+                                        <!-- some dev tools tests need the following properties -->
+                                        <maven.home>${maven.home}</maven.home>
+                                        <maven.repo.local>$${settings.localRepository}</maven.repo.local>
+                                        <maven.settings>$${session.request.userSettingsFile.path}</maven.settings>
+                                        <project.version>${project.version}</project.version>
+                                        <project.groupId>${project.groupId}</project.groupId>

````
However, I still got one failure
````
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.261 s <<< FAILURE! - in org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT
[ERROR] testContent  Time elapsed: 0.061 s  <<< FAILURE!
java.lang.AssertionError: 
[corresponding snapshot file not found for KogitoDMNCodeCodestartIT/testContent/src_test_java_ilove_quark_us_PricingTest.java (Use -Dsnap to create it automatically)] 
Expecting path:
  src/test/resources/__snapshots__/KogitoDMNCodeCodestartIT/testContent/src_test_java_ilove_quark_us_PricingTest.java
to exist (symbolic links were followed).
	at org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT.testContent(KogitoDMNCodeCodestartIT.java:53)
````

Which means the necessary snapshot files will need to be copied to the resources.

**Comment by aloubyansky** [comment]
A couple of options to improve the setup in perspective:
* enhance the generator to extract the resources from the test jar
* make the code start tests look for resources on the classpath

**Comment by radtriste** [comment]
trying with https://repository.jboss.org/nexus/content/groups/public/ which is were you can find current 1.14.1 artifacts

**Comment by radtriste** [comment]
> The artifacts are not available yet unfortunately.

Artifacts are on Jboss Nexus but seems they were not sync on Central. Asking Jboss nexus team about that

**Comment by radtriste** [comment]
> ctual paths on your local machines. E

This does not work for `maven.home` ?

**Comment by aloubyansky** [comment]
Yes, it's kind of weird. Perhaps, omit `maven.home` for now.

**Comment by aloubyansky** [comment]
Unless you copy the snapshots similar to https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L214-L217 it won't work right now. If you don't want to do that, you can simply skip the test for now.

**Comment by gsmet** [comment]
@evacchi @radtriste could you consider moving to s01.oss.sonatype.org to deploy your releases? It's just impossible to do any sort of release planning with repository.jboss.org.

**Comment by radtriste** [comment]
@gsmet I do get it but for now all projects in bsig are deployed through JBoss Nexus.

We do have an issue though: https://issues.redhat.com/browse/BXMSPROD-1513
You may comment there to push a bit forward.

Technically I don't think there is a big difference as sonatype is a Nexus behind so most commands should work there but it is true that this is an external repository and we would depend on it ...

**Comment by gsmet** [comment]
@radtriste I can understand that but from my experience repository.jboss.org sync is too unreliable to plan anything. I think it's too late to have 1.14.1 into 2.5.2 now.

But we really need a new release for 2.6 so we'd better get it sync on time... /cc @evacchi

**Comment by evacchi** [comment]
@radtriste [the timeline for Quarkus 2.6 is](https://github.com/quarkusio/quarkus/wiki/Release-Planning#26-proposal)

- Core Final on December 15th
- Full Platform release (and official announcement) on December 22nd

which means that we have between 15 and 22 to release 1.14.2. As far as I know the fix by @manstis can be easily backported and it is backwards-compatible to 2.5, so we can even start a release immediately after merging that (building against Quarkus 2.5) Is that correct @gsmet ?

**Comment by gsmet** [comment]
@evacchi yes, that's my understanding too. Just be careful, I release on 22nd so you have until 21st.

You can build with 2.5 and you can already test with 2.6.0.CR1 (platform main was already updated).

**Comment by gsmet** [comment]
OK, still nothing on Central. Officially too late.

**Comment by gsmet** [comment]
The artifacts are on Central now.

**Comment by gsmet** [comment]
Per discussion with the Kogito team, we will merge the next release instead.

**Pull request closed without merging**
