### PR TITLE
Upgrade to Camel Quarkus 3.4.0

### PR DESCRIPTION
**Pull request by zbendhiba**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by zbendhiba** [comment]
I'd look at the camel-k-runtime failing tests and disable it.
I think other failures are not related to this

**Comment by gsmet** [comment]
@zbendhiba when doing so, please rebase as it should solve the CXF issues. The Vault issues are not solved yet unfortunately but they are unrelated to your changes.

**Comment by zbendhiba** [comment]
> @zbendhiba when doing so, please rebase as it should solve the CXF issues. The Vault issues are not solved yet unfortunately but they are unrelated to your changes.

okay let me rebase and push again. Sorry for this current build

**Comment by zbendhiba** [comment]
@gsmet  I guess the PR is fine, right?

**Review by gsmet — APPROVED** [review]

**Comment by zbendhiba** [comment]
Thanks @gsmet !

**Pull request merged**
