### PR TITLE
Kogito 1.22.1.Final + OptaPlanner 8.22.1.Final

### PR DESCRIPTION
**Pull request by mbiarnes**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by aloubyansky** [comment]
Re-running

**Review by aloubyansky — APPROVED** [review]
Thanks!

**Comment by aloubyansky** [comment]
Do you want this in 2.9.3.Final? Or only 2.10.x?

**Comment by radtriste** [comment]
if we can have it in 2.9.3 that would be great !

**Comment by aloubyansky** [comment]
Ah, sorry, I didn't realize that. Then it'll target 2.10.x, I suppose. BTW, Guillaume is on PTO, in case you notice him being silent.

**Comment by radtriste** [comment]
ok then for 2.10

**Pull request merged**
