### PR TITLE
Kogito 1.8.0.Final + OptaPlanner 8.8.0.Final

### PR DESCRIPTION
**Pull request by evacchi**
Draft PR with staging repos

### CODE REVIEW

**Comment by aloubyansky** [comment]
@evacchi please also include the changes to the generated platform project. Thanks.

**Comment by gsmet** [comment]
@evacchi you need to run `mvn process-resources` and include the changes in your commit.

**Comment by gsmet** [comment]
Also, if it's supposed to work with 2.0, you should probably enable the components:
- https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L195
- https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L214

**Comment by evacchi** [comment]
running that as we speak (need some time to fetch the dependencies), I am setting those flags to true as well, thanks @gsmet

**Comment by aloubyansky** [comment]
@evacchi i've canceled the current run, given that it doesn't really change anything until you enabled Kogito and OptaPlanner as members.

**Comment by gsmet** [comment]
@evacchi looks like CI passed. I'll let you promote the PR once you have removed the staging repo.

**Comment by gsmet** [comment]
@evacchi when you finalize the PR, I think you will need to rebase as I merged the Camel Quarkus upgrade and rerun mvn process-resources. Maybe just squash everything into 1 commit, otherwise it's going to be a bit hard to do.

**Comment by evacchi** [comment]
@gsmet staging repos removed, squashed, rebased, regenerated 🤞

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
