### PR TITLE
Vault extension 2.0.0

### PR DESCRIPTION
**Pull request by vsevel**
tested with 2.12.0
thanks a lot @kdubb 
cc @aloubyansky

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
Ah, cool, just in time :).

**Comment by kdubb** [comment]
I'm gonna say that is an unrelated failure.

**Comment by aloubyansky** [comment]
FYI @loicmathieu here is another PR (with unrelated changes) where it fails.

**Comment by loicmathieu** [comment]
@aloubyansky is it the only test that fails from time to time or does other platform participant have dangling tests ?
If so, maybe we propose a tag to add to test that should not be run by the platform. I agree it's not a good solution but it allows to blacklist a test and offer time to fix it (at the risk of never fixing it)

**Comment by aloubyansky** [comment]
@loicmathieu you can surely skip a test, for example https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L419-L422 I just wanted to let you know there is an issue.

**Comment by loicmathieu** [comment]
@aloubyansky if I didn't find the issue, I'll disable the test and open an issue on the Quarkiverse repo to avoid forgetting about it.

**Comment by aloubyansky** [comment]
Perfect @loicmathieu, thanks!

**Pull request merged**
