### PR TITLE
Bump Kogito 1.1.0.Final + OptaPlanner 8.1.0.Final

### PR DESCRIPTION
**Pull request by evacchi**

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Please don't merge yet, it has a staging repo.

**Comment by evacchi** [comment]
forgot to mark as draft!

**Comment by evacchi** [comment]
@gsmet ready to go! :)

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
