### PR TITLE
Upgrade to Camel Quarkus 2.13.2

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by gsmet** [comment]
@ppalaga not sure if the CI issue is a flaky test or not?

**Comment by gsmet** [comment]
@ppalaga just a heads up that we plan to release 2.13.7.Final on January 19th so we need this PR merged by January 18th if you want it included in the next 2.13.

Thanks!

**Comment by ppalaga** [comment]
I cannot reproduce the failure locally. Let's see whether it shows up again.

**Comment by ppalaga** [comment]
All tests passed now

**Review by gsmet — APPROVED** [review]

**Pull request merged**
