### PR TITLE
Upgrade to Camel Quarkus 3.2.0

### PR DESCRIPTION
**Pull request by zbendhiba**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by aloubyansky** [comment]
@zbendhiba thanks for noticing, it looks like it's been going on for quite some time. Here is a PR that will let Debezium control its version https://github.com/quarkusio/quarkus-platform/pull/949

**Comment by aloubyansky** [comment]
We should upgrade Debezium to 2.3.0 too, I suppose, since it's available.

**Comment by aloubyansky** [comment]
@zbendhiba if you rebase now, it should preserve Debezium 2.3.0. I think you could also update it to 2.3.2 in a separate commit. Thanks!

**Comment by aloubyansky** [comment]
@zbendhiba so CEQ 3.2.0 can't be added to 3.3 and main yet?

**Comment by zbendhiba** [comment]
@aloubyansky  We can push to main and 3.3.  There will be some tests failing, but it's already the case in 3.3 branch

**Comment by aloubyansky** [comment]
Will it introduce new regressions? If not, I'd proceed with the upgrade.

**Comment by zbendhiba** [comment]
@aloubyansky I missed your last comment. I think we can at least put this final in 3.3. If we can catch a quarkus platform release next week, I can plan releasing one version of camel-quarkus with 3.3

**Comment by aloubyansky** [comment]
Sure, go ahead @zbendhiba

**Pull request merged**
