### PR TITLE
Kogito 1.16.0.Final + OptaPlanner 8.16.0.Final

### PR DESCRIPTION
**Pull request by radtriste**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by radtriste** [comment]
@gsmet @aloubyansky we get that error:
```
2022-01-17T11:32:28.3583721Z [INFO] Running org.kie.kogito.quarkus.workflows.ConversationFlowIT
2022-01-17T11:32:28.3939397Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.03 s <<< FAILURE! - in org.kie.kogito.quarkus.workflows.ConversationFlowIT
2022-01-17T11:32:28.3942306Z [ERROR] org.kie.kogito.quarkus.workflows.ConversationFlowIT  Time elapsed: 0.03 s  <<< ERROR!
2022-01-17T11:32:28.3943664Z java.lang.IllegalStateException: Unable to determine the output of the Quarkus build. Consider setting the 'build.output.directory' system property.
```

Is there a way to solve this ?

**Comment by aloubyansky** [comment]
That looks like something new.

**Comment by radtriste** [comment]
FYI, 1.16.0.Final artifacts have been released on JBoss. Let's hope they reach Maven Central by tomorrow ...

**Comment by radtriste** [comment]
Looks like it is there: https://search.maven.org/artifact/org.kie.kogito/kogito-bom/1.16.0.Final/pom
updating the PR

**Review by gsmet — APPROVED** [review]

**Pull request merged**
