### PR TITLE
Upgrade to Camel Quarkus 2.7.1

### PR DESCRIPTION
**Pull request by zbendhiba**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by zbendhiba** [comment]
I hope this is the right branch version to push Camel quarkus 2.7.x
I guess there are some issues. The new CQ version automates the change of qpid version, and I wonder if it's okay to push those exclusions we have on Debezium ?

**Comment by aloubyansky** [comment]
The exclusions look ok. However, there are version upgrades in the Cassandra's constraints. I'll look into that.

**Comment by zbendhiba** [comment]
I'd check these failures

**Comment by aloubyansky** [comment]
This is Cassandra, which was upgraded to a newer version. I'll release a new version of the platform generator that fixes it and then will ask you to rebase @zbendhiba

**Comment by aloubyansky** [comment]
@zbendhiba could you please rebase your PR? In case you want to keep the exclusion of the `geronimo-jms`, you can add the `dependencyManagement` to the QpidJMS member but they'll have to agree with this change:
````
                             <member>
                                 <name>QpidJMS</name>
                                 <bom>org.amqphub.quarkus:quarkus-qpid-jms-bom:${quarkus-qpid-jms.version}</bom>
                                 <dependencyManagement>
                                     <dependencySpec>
                                         <artifact>org.amqphub.quarkus:quarkus-qpid-jms:${quarkus-qpid-jms.version}</artifact>
                                         <exclusions>
                                             <exclusion>org.apache.geronimo.specs:geronimo-jms_2.0_spec</exclusion>
                                         </exclusions>
                                     </dependencySpec>
                                 </dependencyManagement>
                                 <enabled>true</enabled>
````
Thanks!

**Comment by zbendhiba** [comment]
okay!

**Review by aloubyansky — APPROVED** [review]
Perfect. Thanks a lot @zbendhiba!

**Comment by aloubyansky** [comment]
The same test is failing in the main branch.

**Review by aloubyansky — APPROVED** [review]

**Comment by zbendhiba** [comment]
thanks @aloubyansky

**Pull request merged**
