### PR TITLE
Upgrade Quarkus to 1.11.0.CR1 and Debezium Outbox to 1.4.0.Final

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@ppalaga @jamesnetherton do you think we could disable the failing Camel Quarkus tests for now?

**Comment by jamesnetherton** [comment]
I disabled a couple this morning in https://github.com/quarkusio/quarkus-platform/commit/0067963991cf95242e25d7ffdab22e0ed4a4232a.

The `camel-debezium` tests are already disabled, so if you rerun the workflow, it may pass successfully now.

**Comment by ppalaga** [comment]
Yes, feel free to disable what you need, just please keep us updated what you did so that we know what we need to fix.

**Comment by gsmet** [comment]
Ah, missed the PR, I was on PTO this morning. Thanks! Will rebase and restart CI.

**Pull request merged**
