### PR TITLE
[main] Upgrade Camel Quarkus to 3.0.0-RC2

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Since the Quarkus version is not bumped above 3.2.0, I'd need to disable the SSH & FTP tests again.

**Comment by gsmet** [comment]
@jamesnetherton https://github.com/quarkusio/quarkus-platform/pull/916 is on its way

**Comment by jamesnetherton** [comment]
@gsmet I added a temporary workaround for the google-cloud-pubsub issue. I opened a thread on Zulip to discuss it further.

**Comment by gsmet** [comment]
I'm trying another approach here: https://github.com/quarkusio/quarkus-platform/pull/917 . Let's see how it goes.

**Comment by gsmet** [comment]
I just rebased this one on top of `main` and I think it should get us back to a green state.

**Pull request merged**
