### PR TITLE
Reintroduce Operator SDK in version 6.0.0

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
Are we missing some config in the platform test or are these of different nature?

**Comment by metacosm** [comment]
> Are we missing some config in the platform test or are these of different nature?

Yes, some of our tests require environment variables to be set: https://github.com/quarkiverse/quarkus-operator-sdk/blob/cb5b29925499d9963aa065846c017a4479c39a54/integration-tests/pom.xml#L83-L95

**Comment by gsmet** [comment]
@aloubyansky any chance you could push an additional commit with what is needed to integrate this into the QOSDK tests of the Platform?

**Comment by metacosm** [comment]
If the native tests are also run, you probably need more configuration as well.

**Comment by aloubyansky** [comment]
Closing in favor of https://github.com/quarkusio/quarkus-platform/pull/823

**Pull request closed without merging**
