### PR TITLE
kogito 1.24.0.Final

### PR DESCRIPTION
**Pull request by mbiarnes**
Contains staging repos that should be removed once the Kogito and OptaPlanner artifacts are in Maven Central.

### CODE REVIEW

**Comment by radtriste** [comment]
@mbiarnes there may be some changes to be done on the testing. I will provide a PR to change this tomorrow

**Comment by radtriste** [comment]
Well sooner than expected: https://github.com/mbiarnes/quarkus-platform/pull/11

Let's hope the check is green :)

**Comment by radtriste** [comment]
@aloubyansky @gsmet all good to be merged :)

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
Thanks!

**Pull request merged**
