### PR TITLE
Upgrade Qute Web to 3.1.0

### PR DESCRIPTION
**Pull request by ia3andy**

### CODE REVIEW

**Comment by ia3andy** [comment]
@gsmet it seems the pdfbox was using a wrong version from properties right?

**Review by mkouba — APPROVED** [review]

**Comment by gsmet** [comment]
Yeah, that's just the bom generator that does that. It takes one of the property that matches the version.

**Comment by ia3andy** [comment]
@gsmet error doesn't seem related, we need this for 3.14 platform release (if error is unrelated)

**Comment by ia3andy** [comment]
I rebased if fix was applied on main

**Comment by ia3andy** [comment]
ok I see you merged PR with the same error, I am merging this one

**Pull request merged**
