### PR TITLE
Add Drools Quarkus extension

### PR DESCRIPTION
**Pull request by evacchi**
It is not necessary to include this in the upcoming release, we need to first automate the rest of the steps. Just creating a draft PR to verify that the setup is correct 

/cc @aloubyansky does the main pom.xml look good?
/cc @mariofusco FYI

Blocked by https://github.com/kiegroup/drools/pull/4790 (fixed with the next release)

### CODE REVIEW

**Comment by aloubyansky** [comment]
The `pom.xml` looks ok. What kind of extensions are going to be included in the Drools BOM? Which coderepo is it coming from?

**Comment by evacchi** [comment]
https://github.com/kiegroup/drools/tree/main/drools-drl-quarkus-extension

**Comment by evacchi** [comment]
/cc @mariofusco 

the Drools team would like to provide an extension for Drools with a different purpose from the one in Kogito; indeed, this should also appear on code.quarkus.io if that is what you are asking

**Comment by maxandersen** [comment]
What kind of different purpose?

Will they always stay in sync drools dependency wise ?

**Comment by evacchi** [comment]
that is correct. The Kogito extension provides automated code-generation capabilities (e.g. automatically-generated rest endpoints), while the "plain" Drools extension is for rolling your own REST endpoints and in general interact more "directly" with the Drools engine. The two extensions should also compose (i.e. pulling Kogito Rules + Drools extension would be just redundant, not a conflict). Correct me if I am wrong @mariofusco

**Review by mariofusco — APPROVED** [review]

**Comment by radtriste** [comment]
Thx @evacchi 
I think we will need to take those changes on our Kogito/Optaplanner PR directly so that we are sure we are in sync.
OptaPlanner bom is modified due to this update of Drools. Should OptaPlanner keep a direct dependency to Drools in its bom ?

**Comment by evacchi** [comment]
sure you are free to cherry pick these commits from the other PR if that's what you mean

**Comment by aloubyansky** [comment]
>  Should OptaPlanner keep a direct dependency to Drools in its bom?

That'd be recommended

**Comment by radtriste** [comment]
will be included into https://github.com/quarkusio/quarkus-platform/pull/708
@evacchi I guess you can close this one

**Comment by evacchi** [comment]
🫡

**Pull request closed without merging**
