### PR TITLE
Upgrade to Quarkus 3.12.0.CR1

### PR DESCRIPTION
**Pull request by gsmet**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by gsmet** [comment]
Mmmh, we broke a lot of things...

@ppalaga for Quarkus CXF, I suppose you know what to do as it's related to your patch.

@jamesnetherton @ppalaga There is also a Camel failure related to CouchDB. Not sure if it's a flake or not.

@vsevel @kdubb we broke Quarkus Vault because of the new TLS support. Probably a good idea to discuss this with @geoand and @cescoffier .

```
2024-06-12T11:26:56.0623058Z [ERROR] io.quarkus.vault.VaultAppRoleWrapITCase  Time elapsed: 1.048 s  <<< ERROR!
2024-06-12T11:26:56.0624461Z java.lang.RuntimeException: 
2024-06-12T11:26:56.0625847Z java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2024-06-12T11:26:56.0628114Z 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
2024-06-12T11:26:56.0630241Z [1] Unsatisfied dependency for type io.quarkus.runtime.TlsConfig and qualifiers [@Default]
2024-06-12T11:26:56.0632600Z 	- injection target: parameter 'tlsConfig' of io.quarkus.vault.runtime.client.VaultClientProducer#privateVaultClient()
2024-06-12T11:26:56.0637325Z 	- declared on PRODUCER METHOD bean [types=[io.quarkus.vault.client.VaultClient, io.quarkus.vault.client.common.VaultRequestExecutor, java.lang.Object], qualifiers=[@Private, @Any], target=io.quarkus.vault.client.VaultClient privateVaultClient(io.quarkus.vault.runtime.VaultConfigHolder vaultConfigHolder, io.quarkus.runtime.TlsConfig tlsConfig), declaringBean=io.quarkus.vault.runtime.client.VaultClientProducer]
2024-06-12T11:26:56.0641362Z [2] Unsatisfied dependency for type io.quarkus.runtime.TlsConfig and qualifiers [@Default]
2024-06-12T11:26:56.0643227Z 	- injection target: parameter 'tlsConfig' of io.quarkus.vault.runtime.client.VaultClientProducer#sharedVaultClient()
2024-06-12T11:26:56.0648221Z 	- declared on PRODUCER METHOD bean [types=[io.quarkus.vault.client.VaultClient, io.quarkus.vault.client.common.VaultRequestExecutor, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.vault.client.VaultClient sharedVaultClient(io.vertx.core.Vertx vertx, io.quarkus.vault.runtime.VaultConfigHolder vaultConfigHolder, io.quarkus.runtime.TlsConfig tlsConfig), declaringBean=io.quarkus.vault.runtime.client.VaultClientProducer]
2024-06-12T11:26:56.0652507Z 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1554)
2024-06-12T11:26:56.0653818Z 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
2024-06-12T11:26:56.0655050Z 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
2024-06-12T11:26:56.0656300Z 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
2024-06-12T11:26:56.0657921Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-06-12T11:26:56.0659485Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-06-12T11:26:56.0661265Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-06-12T11:26:56.0662788Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-06-12T11:26:56.0663910Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
2024-06-12T11:26:56.0665014Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
2024-06-12T11:26:56.0666065Z 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2024-06-12T11:26:56.0667344Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
2024-06-12T11:26:56.0668791Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
2024-06-12T11:26:56.0670233Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
2024-06-12T11:26:56.0671773Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-12T11:26:56.0672853Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
2024-06-12T11:26:56.0674638Z 	Suppressed: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.runtime.TlsConfig and qualifiers [@Default]
2024-06-12T11:26:56.0677082Z 	- injection target: parameter 'tlsConfig' of io.quarkus.vault.runtime.client.VaultClientProducer#privateVaultClient()
2024-06-12T11:26:56.0681838Z 	- declared on PRODUCER METHOD bean [types=[io.quarkus.vault.client.VaultClient, io.quarkus.vault.client.common.VaultRequestExecutor, java.lang.Object], qualifiers=[@Private, @Any], target=io.quarkus.vault.client.VaultClient privateVaultClient(io.quarkus.vault.runtime.VaultConfigHolder vaultConfigHolder, io.quarkus.runtime.TlsConfig tlsConfig), declaringBean=io.quarkus.vault.runtime.client.VaultClientProducer]
2024-06-12T11:26:56.0685806Z 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
2024-06-12T11:26:56.0686931Z 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:642)
2024-06-12T11:26:56.0688031Z 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
2024-06-12T11:26:56.0688902Z 		... 14 more
2024-06-12T11:26:56.0690339Z 	Suppressed: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.runtime.TlsConfig and qualifiers [@Default]
2024-06-12T11:26:56.0692799Z 	- injection target: parameter 'tlsConfig' of io.quarkus.vault.runtime.client.VaultClientProducer#sharedVaultClient()
2024-06-12T11:26:56.0697911Z 	- declared on PRODUCER METHOD bean [types=[io.quarkus.vault.client.VaultClient, io.quarkus.vault.client.common.VaultRequestExecutor, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.vault.client.VaultClient sharedVaultClient(io.vertx.core.Vertx vertx, io.quarkus.vault.runtime.VaultConfigHolder vaultConfigHolder, io.quarkus.runtime.TlsConfig tlsConfig), declaringBean=io.quarkus.vault.runtime.client.VaultClientProducer]
2024-06-12T11:26:56.0702145Z 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
2024-06-12T11:26:56.0703252Z 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:642)
2024-06-12T11:26:56.0704326Z 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
2024-06-12T11:26:56.0705163Z 		... 14 more
```

**Comment by cescoffier** [comment]
@gsmet The TlsConfig issue was somewhat expected. For wrong reasons, this was a build time config. We made it runtime for obvious reasons - but it cannot be injected. 

We have two choices:
- we can edit the code to read the property (they need a single one) properly
- we do the work to integrate with the TLS registry

I would prefer the second one, but it might take a day or two (I'm off Friday).

**Comment by cescoffier** [comment]
Hum, thinking about it. If we want to have a single code base for both the LTS and 3.12+, we may need to use the first approach.

**Comment by geoand** [comment]
> Hum, thinking about it. If we want to have a single code base for both the LTS and 3.12+, we may need to use the first approach.

Yes, if Vault is to support both, there is no other way

**Comment by geoand** [comment]
I'll open a PR for Vault

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-vault/pull/285

**Comment by cescoffier** [comment]
Damend, I did the same :-)

**Comment by geoand** [comment]
😎

**Comment by jamesnetherton** [comment]
The CouchDB failure is a [known issue](https://github.com/apache/camel-quarkus/issues/6148). It'll get resolved when we integrate CQ 3.12.0

**Pull request merged**
