### PR TITLE
Update QOSSDK to 5.1.1

### PR DESCRIPTION
**Pull request by metacosm**
- Update QOSDK to 5.1.0
- Update QOSDK to 5.1.1, skipping failing tests for now

Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by aloubyansky** [comment]
Different error in a Camel test this time.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
AFAICS, failure is:
```
	Caused by: org.openstack4j.api.exceptions.OS4JException: Unable to retrieve current session. Please verify thread has a current session available.
		at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:106)
		at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:100)
		at org.openstack4j.openstack.internal.BaseOpenStackService.get(BaseOpenStackService.java:46)
		at org.openstack4j.openstack.identity.v3.internal.RegionServiceImpl.get(RegionServiceImpl.java:36)
		at org.apache.camel.component.openstack.keystone.producer.RegionProducer.doGet(RegionProducer.java:73)
		at org.apache.camel.component.openstack.keystone.producer.RegionProducer.process(RegionProducer.java:48)
		at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
		at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:214)
		at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111)
		at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
```

I don't see how it could be related but I saw you restarted CI so let's see how it goes.

**Comment by aloubyansky** [comment]
Now it passed. But previous two runs had different failures, afair.

**Comment by gsmet** [comment]
Yes I think we can go ahead.

**Pull request merged**
