### PR TITLE
Upgrade to Camel Quarkus 3.11.0

### PR DESCRIPTION
**Pull request by zbendhiba**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by zbendhiba** [comment]
Hello @aloubyansky @gsmet 
I noticed that the `./mvnw -Dsync`moved many `${camel-quarkus.version}`to `3.11.0`. I'm not sure if that is expected or not ?

**Comment by aloubyansky** [comment]
It's ok, it's a coincidence of having Quarkus core version matching Camel Quarkus version and the generator could not decide which property to use.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
> I noticed that the ./mvnw -Dsyncmoved many ${camel-quarkus.version}to 3.11.0. I'm not sure if that is expected or not ?

Yeah it is a bit annoying as it generates a lot of noise in the PR but basically Maven randomly (probably not randomly but you get the point) chooses a property that match the version. So when updating a given version, and you have a property that matches, it will pick one and it might not be the previous one.

**Comment by zbendhiba** [comment]
Thanks for the explanations @gsmet @aloubyansky

**Pull request merged**
