### PR TITLE
Switch to Eclipse Temurin JDK

### PR DESCRIPTION
**Pull request by famod**
Just like https://github.com/quarkusio/quarkus/pull/19414

### CODE REVIEW

**Comment by aloubyansky** [comment]
@gsmet just fyi, I noticed
````
ANTLR Runtime version 4.9.2 used for parser compilation does not match the current runtime version 4.8ANTLR Runtime version 4.9.2 used for parser compilation does not match the current runtime version 4.8
````
in the logs

**Comment by aloubyansky** [comment]
@gsmet should we backport it?

**Comment by gsmet** [comment]
No it's just CI, we can keep the current JDK in the old branch.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Yeah the Antlr issue has been here for a while.

IIRC, we have some parts using 4.8 and some parts using the new one, so in any case, there's a mismatch.

**Comment by famod** [comment]
I took a stab at that ANTLR problem: https://github.com/quarkusio/quarkus/pull/19551

**Pull request merged**
