### PR TITLE
Upgrade to Google Cloud Services 2.0.0

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@loicmathieu could you check the CI error? Is it something we had before?

**Comment by gsmet** [comment]
The problem is due to JUnit Pioneer and might be due to the fact that we are now testing with Java 17.

```
2023-04-13T15:02:57.0377179Z [ERROR] testBigtable  Time elapsed: 0.565 s  <<< ERROR!
2023-04-13T15:02:57.0378948Z java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.HashMap java.lang.ProcessEnvironment.theEnvironment accessible: module java.base does not "opens java.lang" to unnamed module @43c3d622
2023-04-13T15:02:57.0380110Z 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
2023-04-13T15:02:57.0381875Z 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
2023-04-13T15:02:57.0384386Z 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
2023-04-13T15:02:57.0385226Z 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
2023-04-13T15:02:57.0386003Z 	at org.junitpioneer.jupiter.EnvironmentVariableUtils.getFieldValue(EnvironmentVariableUtils.java:98)
2023-04-13T15:02:57.0527520Z 	at org.junitpioneer.jupiter.EnvironmentVariableUtils.setInProcessEnvironmentClass(EnvironmentVariableUtils.java:78)
2023-04-13T15:02:57.0528802Z 	at org.junitpioneer.jupiter.EnvironmentVariableUtils.modifyEnvironmentVariables(EnvironmentVariableUtils.java:50)
2023-04-13T15:02:57.0529613Z 	at org.junitpioneer.jupiter.EnvironmentVariableUtils.set(EnvironmentVariableUtils.java:36)
2023-04-13T15:02:57.0530368Z 	at org.junitpioneer.jupiter.EnvironmentVariableExtension.setEntry(EnvironmentVariableExtension.java:68)
2023-04-13T15:02:57.0531165Z 	at org.junitpioneer.jupiter.EnvironmentVariableExtension.setEntry(EnvironmentVariableExtension.java:18)
```

@loicmathieu I will let you have a look at this issue.

**Comment by gsmet** [comment]
@aloubyansky do we have an easy way to pass some `--add-opens` options to a test execution?

**Comment by gsmet** [comment]
Yes that would be it. Even if we end up finding another solution, it's probably a good idea to have it handy.

**Comment by loicmathieu** [comment]
@gsmet the following add-opens needs to be set. If it's not possible we'll need to disable this test as it set a system variable via reflection.

```
--add-opens java.base/java.util=ALL-UNNAMED
--add-opens java.base/java.lang=ALL-UNNAMED
```

I also note that there is CI failures for OpenTelemetryc exporters, they recently add support for Google Cloud but they didn't use the gRPC support provided by the Google Cloud Service extension pack so we may end up with multiple substitutions and I think it is not supported by GraalVM to substitute the same class multiple times. I didn't look at it in details but it may be the issue.

**Comment by aloubyansky** [comment]
I opened https://github.com/quarkusio/quarkus-platform/pull/814 with the new `argLine` config.

**Comment by aloubyansky** [comment]
#814 worked, I'm closing this one.

**Pull request closed without merging**
